/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//汉化杂项
var cnItems = {
    _OTHER_: [],
    //#region 主界面等
    '.': '。',
    'Loading game...': '载入游戏中……',
    'You were gone offline for ': '您离线了',
    'Your mass\'s exponent': '您质量的指数',
    ' is increased by ': '增加了',
    'Your mass\'s exponent is increased by ': '您质量的指数增加了',
    'Your exponent': '您黑洞质量的指数',
    ' of mass of black hole is increased by ': '增加了',
    'Your exponent of mass of black hole is increased by ': '您黑洞质量的指数增加了',
    'Your quark\'s exponent': '您夸克的指数',
    'Your quark\'s exponent is increased by ': '您夸克的指数增加了',
    'You were becomed ': '您前往了',
    ' more supernovas.': '次超新星。',
    'softcapped': '受软上限限制',
    'softcapped^2': '受二重软上限限制',
    'softcapped^3': '受三重软上限限制',
    'Main': '主要',
    'Mass': '质量',
    'Black Hole': '黑洞',
    'Atomic Generator': '原子发生器',
    'Stars': '星辰',
    'Indescribable Matter': '无法形容之物',
    'The Parallel': '平行',
    'Stats': '统计',
    'Ranks Rewards': '级别奖励',
    'Scaling': '折算',
    'Prestige Rewards': '转生奖励',
    'Beyond-Ranks Rewards': '超-级别奖励',
    'Upgrades': '升级',
    'Challenges': '挑战',
    'Quantum Challenge': '量子挑战',
    'Atom': '原子',
    'Particles': '粒子',
    'Elements': '元素',
    'Mass Dilation': '质量膨胀',
    'Break Dilation': '撕裂膨胀',
    'Exotic Atoms': '奇异原子',
    'Supernova': '超新星',
    'Neutron Tree': '中子树',
    'Bosons': '玻色子',
    'Fermions': '费米子',
    'Radiation': '辐射波',
    'Quantum': '量子',
    'Chroma': '色度',
    'Quantum Milestones': '量子里程碑',
    'Auto-Quantum': '自动前往量子',
    'Primordium': '原基',
    'Entropy': '熵',
    'Darkness': '黑暗',
    'Dark Effects': '黑暗效果',
    'Dark Run': '黑暗狂奔',
    'The Matters': '物质',
    'Corruption': '腐化',
    'Infinity': '无限',
    'Core': '核心',
    'Core Effect': '核心效果',
    'Infinity Upgrades': '无限升级',
    'Options': '选项',
    'Resource Hider': '隐藏资源',
    'Ranks': '级别',
    'Prestiges': '转生',
    'Buy Max': '最大化购买',
    'ON': '开启',
    'OFF': '关闭',
    'Super': '超级折算',
    'Hyper': '究极折算',
    'Ultra': '超究折算',
    'Meta': '元折算',
    'Exotic': '奇异折算',
    'Supercritical': '超临界折算',
    'Super ': '超级折算|',
    'Hyper ': '究极折算|',
    'Ultra ': '超究折算|',
    'Meta-': '元折算|',
    'Exotic ': '奇异折算|',
    'Supercritical ': '超临界折算|',
    'Muscler [': '锻体器[',
    'Booster [': '助推器[',
    'Stronger [': '强化器[',
    'Overpower [': '降伏器[',
    'Tickspeeds [': '时间速度[',
    ' Rage Power': '狂怒能量',
    'Tickspeed Power': '时间速度倍率',
    'Tickspeed Effect': '时间速度效果',
    ' to mass gain': '质量获取速度',
    'Accelerators [': '加速器[',
    'Accelerator Power': '加速器倍率',
    'Accelerator Effect': '加速器效果',
    'After ': '当到达',
    ' of mass gain, mass gain will be softcapped!': '的质量获取速度以后，质量获取速度将受到软上限限制！',
    ' of mass gain will softcap^2 mass gain!': '的质量获取速度以后，质量获取速度将受到二重软上限限制！',
    ' of mass gain will softcap^3 mass gain!': '的质量获取速度以后，质量获取速度将受到三重软上限限制！',
    ' of mass gain will softcap^4 mass gain!': '的质量获取速度以后，质量获取速度将受到四重软上限限制！',
    ' of mass gain will softcap^5 mass gain!': '的质量获取速度以后，质量获取速度将受到五重软上限限制！',
    ' of mass gain will softcap^6 mass gain!': '的质量获取速度以后，质量获取速度将受到六重软上限限制！',
    ' of mass gain will softcap^7 mass gain!': '的质量获取速度以后，质量获取速度将受到七重软上限限制！',
    ' of mass gain will softcap^8 mass gain!': '的质量获取速度以后，质量获取速度将受到八重软上限限制！',
    'Because of mass overflow at ': '因为质量超过了',
    ', your mass gain is raised by ': '，发生溢出，因此它变为了以下次方：',
    ', your mass gain is rooted by ': '，发生溢出，因此它变为了以下次方根：',
    'Because of mass overflow^2 at ': '因为质量超过了',
    ', your mass overflow is even stronger!': '，发生二重溢出，它变得更严重了！',
    'Because of stronger overflow at ': '因为强化器超过了',
    ', your stronger effect is raised by ': '，发生溢出，因此强化器效果变为了以下次方：',
    ', your stronger effect is rooted by ': '，发生溢出，因此强化器效果变为了以下次方根：',
    'Because of stronger overflow^2 at ': '因为强化器超过了',
    ', your stronger overflow is even stronger!': '，发生二重溢出，它变得更严重了！',
    'Your Prestige base is ': '您的转生基础值为',
    ' (based on product of Rank tiers': '(基于级别、阶层、四重阶层和五重阶层的数值而定',
    ' of Black Hole': '黑洞',
    'Which boosts mass gain by ': '它使质量获取速度增加',
    'Black Hole mass\'s gain formula - (x + 1': '黑洞质量获取公式为：(x + 1',
    ' of Unstable Black Hole': '不稳定黑洞',
    'Which boosts mass of black hole gain by ': '它使黑洞质量获取速度增加',
    'Unstable BH\'s production is decreased based on its mass': '不稳定黑洞的获取速度基于它的质量而减少',
    'Black Hole Condensers [': '黑洞压缩器[',
    ' Dark Matters': '暗物质',
    'BH Condenser Power': '黑洞压缩器倍率',
    'False Vacuum Manipulators [': '假真空操控器[',
    ' Dark Matters in C16': '挑战16中的暗物质',
    'FV Manipulator Power': '假真空操控器倍率',
    'FV Manipulator Effect': '假真空操控器效果',
    ' to Unstable BH production speed': '不稳定黑洞的获取速度',
    ' of mass gain from black hole, its mass gain will be softcapped!': '的黑洞质量获取速度以后，质量获取速度将受到软上限限制！',
    'The formula (x + 1': '公式(x + 1',
    ' softcaps at ': '的软上限为',
    'Because of black hole mass overflow at ': '因为黑洞质量超过了',
    ', your mass of black hole gain is raised by ': '，发生溢出，因此它变为了以下次方：',
    ', your mass of black hole gain is rooted by ': '，发生溢出，因此它变为了以下次方根：',
    'Because of black hole mass overflow^2 at ': '因为黑洞质量超过了',
    ', your black hole mass overflow is even stronger!': '，发生二重溢出，它变得更严重了！',
    ' Atomic Power': '原子能量',
    'Which provides ': '它使您获得了',
    ' free Tickspeeds': '个免费时间速度升级',
    'Cosmic Rays [': '宇宙射线[',
    ' Atoms': '原子',
    'Cosmic Ray Power': '宇宙射线倍率',
    'Cosmic Ray Effect': '宇宙射线效果',
    'Because of atomic power overflow at ': '因为原子能量超过了',
    ', your atomic power gain is raised by ': '，发生溢出，因此它变为了以下次方：',
    ', your atomic power gain is rooted by ': '，发生溢出，因此它变为了以下次方根：',
    'You collapsed ': '您已经坍缩了',
    ' stars, which multiplies mass gain based on all rank types.': '星辰，质量获取速度基于级别的种类而增加',
    ' Collapsed stars gain, Collapsed stars gain will be softcap!': '的坍缩星辰以后，坍缩星辰获取速度将受到软上限限制！',
    ' Blueprint Particles': '蓝图粒子',
    'Which increases pre-Quantum global speed by ': '它使量子之前所有资源获取速度变为原来的',
    'Cosmic Strings [': '宇宙弦[',
    ' Quantum Foam': '量子泡沫',
    'Cosmic Strings Power': '宇宙弦倍率',
    'Cosmic Strings Effect': '宇宙弦效果',
    ' of dimensional mass': '维度质量',
    'Which boosts meta-score of equipped theorems by ': '它使已装备定理的综合评分增加',
    'Parallel Extruder [': '平行挤出机[',
    ' Infinity Points': '无限点数',
    'Parallel Extruder Power': '平行挤出机倍率',
    'Parallel Extruder Effect': '平行挤出机效果',
    ' to dimensional mass gain': '维度质量的获取速度',
    //#endregion
    //#region 提示框
    'You have pushed ': '您推动了',
    'Rage Power': '狂怒能量',
    'Reach over ': '到达超过',
    ' of normal mass to reset previous features for gain Rage Powers.': '质量才可以重置之前的机制，获得狂怒能量。',
    'Dark Matter': '暗物质',
    ' Rage Power to reset all previous features for gain Dark Matters.': '狂怒能量才可以重置之前的机制，获得暗物质。',
    ' of black hole.': '黑洞质量。',
    ' of Unstable Black Hole.': '不稳定黑洞质量。',
    ' of black hole to reset all previous features for gain Atoms & Quarks.': '黑洞质量才可以重置之前的机制，获得原子和夸克。',
    'Quark': '夸克',
    ' Quark.': '夸克。',
    ' Exotic Atoms.': '奇异原子。',
    ' of dilated mass.': '膨胀质量。',
    ' Relativistic Energy.': '相对论能量。',
    ' of Relativistic Mass.\n            ': '相对论质量。',
    'Reach ': '到达',
    ' of normal mass to gain Relativistic Particles, or cancel dilation.': '质量后可以获得相对论粒子，点击取消质量膨胀。',
    'Dilate mass, then cancel.': '使质量膨胀，然后再取消。',
    'Dilating mass will force an atom reset. While mass is dilated, all pre-atom resources and atomic power gain will get their multipliers\' exponents raised to 0.8': '进行质量膨胀时将同时进行一次原子重置，质量膨胀时，所有原子之前的资源，及原子能量获取速度变为原来的0.8次方。',
    'You have becomed ': '您前往了',
    ' Collapsed Star.': '坍缩星辰。',
    ' Neutron Star.': '中子星。',
    ' collapsed stars to go Supernova.': '坍缩星辰后可以前往超新星。',
    'Quantum Foam': '量子泡沫',
    ' of normal mass to complete Quantum Challenge.': '质量来完成量子挑战。',
    ' of normal mass to go Quantum.': '质量来前往量子。',
    'Death Shard': '死寂碎片',
    'Big Rip the Dimension, then go back.': '使维度大撕裂，然后再返回。',
    'While in Big Rip, Entropy Rewards don\'t work, all Primordium effects are 50% weaker except for Epsilon Particles, which don\'t work, supernova tree upgrades qu2 and qu10 don\'t work, and you are trapped in Quantum Challenge with modifiers [10,2,10,10,5,0,2,10]. Death Shards are gained based on your normal mass while in Big Rip. Unlock various upgrades from Big Rip.': '大撕裂维度后，熵的加成失效，所有原基粒子的效果减半，艾普西隆粒子完全失效，中子树升级[qu2]和[qu10]失效，且您强制以[10,2,10,10,5,0,2,10]的配置进行量子挑战。但大撕裂维度后，您可以根据质量获得死寂碎片。您可以使用死寂碎片解锁新升级。',
    'Dark Ray': '暗射线',
    ' Abyssal Blot.': '深渊之渍。',
    'Require ': '需要',
    'Oganesson-118': '气奥(118Og)',
    ' to go Dark.': '才能融入黑暗。',
    'Global Speed': '所有资源获取速度',
    'Pre-Quantum: Speeds up the production of pre-Quantum resources (after exponent, dilation, etc.).': '量子之前：加快量子之前所有资源获取速度(在计算完指数和膨胀等之后的数值)。',
    'Pre-Infinity: Speeds up the production of pre-Infinity resources. Applies pre-Quantum global speed. (after exponent, dilation, etc.)': '无限之前：加快无限之前所有资源获取速度(在计算完指数和膨胀等之后的数值)。使用量子之前所有资源获取速度。',
    'Final Star Shard (FSS': '最终星辰碎片(物质',
    'Your FSS base is ': '您的最终星辰碎片基础值为',
    ' of FSS\'s base to get Final Star Shard.': '最终星辰碎片基础值才能获得最终星辰碎片。',
    'Corrupted Shard': '腐化碎片',
    'Corrupted Shards': '腐化碎片',
    'Start the 16th Challenge. Earn ': '进入挑战16以后，可以根据黑洞质量获得',
    ' based on your mass of black hole, when exiting the challenge with more than ': '，这需要在退出挑战时达到',
    'Your Infinity Theorem is ': '您的无限定理为',
    ' of normal mass to get Infinity Points and choose Theorem in Core.': '质量后可以获得无限点数，并可以在核心子选项卡下选择定理。',
    'Your normal mass limit is ': '您的质量上限为',
    'Going Infinity resets everything darkness as well!': '前往无限会重置之前所有东西，包括黑暗！',
    //#endregion
    //#region 统计
    'Rank': '级别',
    'Tier': '阶层',
    'Tetr': '四重阶层',
    'Pent': '五重阶层',
    'Hex': '六重阶层',
    'Mass Upgrades 1-3': '质量升级1-质量升级3',
    'Tickspeed': '时间速度',
    'Black Hole Condenser': '黑洞压缩器',
    'Cosmic Ray': '宇宙射线',
    'Fermion Tier': '费米子阶层',
    'Cosmic String': '宇宙弦',
    'Prestige Level': '转生等级',
    'Honor': '荣耀',
    'Glory': '赞颂',
    'Renown': '名望',
    'Overpower': '降伏器',
    'Final Star Shard': '最终星辰碎片',
    'Parallel Extruder': '平行挤出机',
    '): Starts at ': ')：开始次数为',
    //#endregion
    //#region 升级
    'Rage Upgrades': '狂怒升级',
    'Boosters add Musclers.': '使助推器可以增加锻体器数量。',
    'Strongers add Boosters.': '使强化器可以增加助推器数量。',
    'You can automatically buy mass upgrades.': '您可以自动购买质量升级。',
    'Ranks no longer reset anything.': '级别不再重置任何东西。',
    'You can automatically rank up.': '您可以自动提升级别。',
    'You can automatically tier up.': '您可以自动提升阶层。',
    'For every 3 tickspeeds add Stronger.': '每购买3次时间速度，就增加1个强化器。',
    'Super and Hyper mass upgrade scalings are weaker based on Rage Power.': '使质量升级的超级折算和究极折算基于狂怒能量的数值而弱化。',
    'Stronger power is increased by +^0.25.': '使强化器倍率的效果指数增加0.25',
    'Super Rank scaling is 20% weaker.': '使级别的超级折算弱化20%。',
    'Black Hole mass\'s gain is boosted by Rage Point.': '使黑洞质量的获取速度基于狂怒能量的数值变得更多。',
    'OoMs of Rage powers increase stronger power at a reduced rate.': '使狂怒能量的数量级可以增加强化器倍率，只是效果倍率降低。',
    'Mass gain softcap starts 3x later for every Rank you have.': '每有一个级别，质量获取速度的软上限就延迟3倍出现。',
    'Hyper Tickspeed starts 50 later.': '使时间速度的究极折算延迟50次出现。',
    'Mass boosts Atom gain.': '使质量可以加成原子获取速度。',
    'Remove tickspeed power\'s softcap.': '移除时间速度倍率的软上限。',
    'Overpower power is increased by 0.005.': '使降伏器倍率增加0.005。',
    'Fading matter\'s upgrade applies to rage powers gain at a reduce rate.': '使褪色物质的升级可以对狂怒能量获取速度生效，只是效果倍率降低。',
    'Supernovas boost overpower power.': '使超新星次数可以加成降伏器倍率。',
    'Corrupted Shards boost normal mass gain.': '使腐化碎片可以加成质量获取速度。',
    'Black Hole Upgrades': '黑洞升级',
    'Mass Upgardes no longer spend mass.': '购买质量升级不再花费质量。',
    'Tickspeeds boost BH Condenser Power.': '使时间速度可以加成黑洞压缩器倍率。',
    'Super Mass Upgrade scales later based on mass of Black Hole.': '使质量升级的超级折算基于黑洞质量的数值而延迟出现。',
    'Tiers no longer reset anything.': '阶层不再重置任何东西。',
    'You can automatically buy tickspeed and Rage Power upgrades.': '您可以自动购买时间速度升级和狂怒能量升级。',
    'Gain 100% of Rage Power gained from reset per second. Rage Powers are boosted by mass of Black Hole.': '每秒获得狂怒能量，数量为重置时获取数量的100%。使狂怒能量获取速度基于黑洞质量的数值而增加。',
    'Mass gain softcap starts later based on mass of Black Hole.': '使质量获取速度的软上限基于黑洞质量的数值而延迟出现。',
    'Raise Rage Power gain by 1.15.': '使狂怒能量获取速度变为原来的1.15次方。',
    'Stronger Effect\'s softcap starts later based on unspent Dark Matters.': '使强化器的软上限基于未花费的暗物质数值而延迟出现。',
    'Mass gain is boosted by OoM of Dark Matters.': '使质量获取速度基于暗物质的数量级而增加。',
    'Mass gain softcap is 10% weaker.': '使质量获取速度的软上限弱化10%。',
    'Hyper Tickspeed scales 15% weaker.': '使时间速度的究极折算弱化15%。',
    'Quark gain is multiplied by 10.': '使夸克获取速度变为原来的10倍。',
    'Neutron Powers boost mass of Black Hole gain.': '使中子能量可以加成黑洞质量获取速度。',
    'Atomic Powers add Black Hole Condensers at a reduced rate.': '使原子能量可以增加黑洞压缩器的数量，只是效果倍率降低。',
    'Red matter\'s upgrade applies to mass gain at a reduced rate.': '使红色物质的升级可以对质量获取速度生效，只是效果倍率降低。',
    'Violet matter\'s upgrade applies to collapsed stars at a reduced rate.': '使蓝紫色物质的升级可以对坍缩星辰获取速度生效，只是效果倍率降低。',
    'Make black hole\'s effect stronger.': '使黑洞的效果变得更好。',
    'Mass of black hole boosts accelerator power at an extremely reduced rate.': '使黑洞质量可以加成加速器倍率，只是效果倍率极度降低。',
    'Corrupted Shards boost mass of black hole gain.': '使腐化碎片可以加成黑洞质量获取速度。',
    'Atom Upgrades': '原子升级',
    'Start with Mass upgrades unlocked.': '初始状态下就解锁质量升级。',
    'You can automatically buy BH Condenser and upgrades. Tickspeed no longer spends Rage Powers.': '您可以自动购买黑洞压缩器和黑洞升级。购买时间速度不再花费狂怒能量。',
    '[Tetr Era] Unlock Tetr.': '[四重阶层纪元]解锁四重阶层。',
    'Keep challenges 1-4 on reset. BH Condensers add Cosmic Rays Power at a reduced rate.': '重置时保留挑战1-挑战4的完成次数。使黑洞压缩器可以增加宇宙射线的数量，只是效果倍率降低。',
    'You can automatically Tetr up. Super Tier starts 10 later.': '您可以自动提升四重阶层。阶层的超级折算延迟10次出现。',
    'Gain 100% of Dark Matters gained from reset per second. Mass gain from Black Hole softcap starts later based on Atomic Powers.': '每秒获得暗物质，数量为重置时获取数量的100%。使黑洞质量获取速度的软上限基于原子能量的数值而延迟出现。',
    'Tickspeed boosts each particle powers gain.': '使时间速度可以加成粒子能量的获取速度。',
    'Atomic Powers boost Quark gain.': '使原子能量可以加成夸克的获取速度。',
    'Stronger effect softcap is 15% weaker.': '使强化器效果的软上限弱化15%。',
    'Tier requirement is halved. Hyper Rank starts later based on Tiers you have.': '使阶层的需求减半。使级别的究极折算基于目前的阶层数值而延迟出现。',
    'Dilated mass also boosts BH Condenser & Cosmic Ray powers at a reduced rate.': '使膨胀质量可以加成黑洞压缩器倍率和宇宙射线倍率，只是效果倍率降低。',
    'Mass from Black Hole effect is better.': '使黑洞质量效果变得更好。',
    'Cosmic Ray effect softcap starts x10 later.': '使宇宙射线效果的软上限延迟10倍出现。',
    'Tickspeed, Black Hole Condenser and Cosmic Ray scalings up to Meta start x10 later.': '使时间速度、黑洞压缩器和宇宙射线到元折算为止的所有折算延迟10倍出现。',
    'Reduce Cosmic Ray scaling by 20%.': '使宇宙射线的所有折算弱化20%。',
    'Quark Overflow starts ^10 later.': '使夸克的溢出延迟10次方出现。',
    'Pink matter\'s upgrade applies to quark gain at a reduced rate.': '使粉色物质的升级可以对夸克获取速度生效，只是效果倍率降低。',
    'Neutron Power\'s second effect now provides an expontial boost and applies to mass of black hole.': '使中子能量的第二个效果变为指数加成，且可以对黑洞质量生效。',
    'Yellow matter\'s upgrade applies to dilated mass overflow at a reduced rate.': '使黄色物质的升级可以让膨胀质量的溢出延迟出现，只是效果倍率降低。',
    'Atomic Powers add Overpowers at an extremely reduced rate.': '使原子能量可以增加降伏器的数量，只是效果倍率极度降低。',
    'Big Rip Upgrades': '大撕裂升级',
    'Start with Hydrogen-1 unlocked in Big Rip.': '在大撕裂中，初始状态下就解锁氢(1H)。',
    'Mass Upgrades & Ranks are no longer nerfed by 8th QC modifier.': '使质量升级和级别不再受到量子挑战8的削弱。',
    'Pre-Quantum Global Speed is raised based on Death Shards (before division).': '使量子之前所有资源获取速度基于死寂碎片数量而增加(在计算削弱之前生效)。',
    'Start with 2 tiers of each Fermion in Big Rip.': '在大撕裂中，初始状态下就获得所有费米子各2阶层。',
    'Root Star Booster’s starting cost by 10. Star Booster’s base is increased based on Death Shards.': '使星辰发生器的初始花费变为原来的0.1次方，效果基于死寂碎片数量而增加。',
    'Start with all Radiation features unlocked.': '初始状态下就解锁所有辐射波。',
    'Hybridized Uran-Astatine is twice as effective in Big Rip.': '在大撕裂中，使铀砹混合物的效果翻倍。',
    'Passively gain 10% of Quantum Foams & Death Shards you would get from resetting each second.': '每秒获得量子泡沫和死寂碎片，数量为重置时获取数量的10%。',
    'Unlock Break Dilation and Prestige (in the mass tab).': '解锁撕裂膨胀和转生(在主要选项卡的质量子选项卡下)。',
    'Chromas are 10% stronger.': '色度的效果增加10%。',
    'Prestige Level no longer resets anything.': '转生等级不再重置任何东西。',
    'Mass gain softcap^5 starts later based on Atom.': '使质量获取速度的五重软上限基于原子的数值而延迟出现。',
    'Death Shard gain is boosted based on Prestige Base.': '使死寂碎片获取速度基于转生基础值而增加。',
    'Super Fermion Tier starts 10 later (after QC8 nerf).': '使费米子阶层的超级折算延迟10次出现(在计算量子挑战8的削弱之后生效)。',
    'Blueprint Particles boost Pre-Quantum Global Speed slightly.': '使蓝图粒子的量子之前所有资源获取速度略微增加。',
    'Unsoftcap the first effect from Alpha, Omega & Sigma particles. They\'re stronger.': '移除阿尔法粒子第一个效果、欧米伽粒子第一个效果和西格马粒子第一个效果的软上限，且它们的效果变得更好。',
    'Dark matter raises atoms gain at a reduced rate.': '使暗物质可以加成原子获取速度，只是效果倍率降低。',
    'Chromas gain is boosted by mass.': '使色度获取速度基于质量的数值而增加。',
    'Red Matters reduce Pre-Renown requirements slightly.': '使红色质量可以略微减少名望之前所有转生的需求。',
    'Total corrupted Shards boost dark rays gain.': '使腐化碎片的总数可以加成暗射线的获取速度。',
    //#endregion
    //#region 挑战
    'Note: Click any image to show challenge description. Click again to enter any challenge': '提示：点击图片以查看挑战详情。再次点击该挑战后将进入该挑战。',
    'Exit Challenge': '退出挑战',
    'Enter Challenge': '进入挑战',
    'Super rank and mass upgrade scaling starts at 25. Also, Super tickspeed starts at 50.': '级别和质量升级的超级折算在25次就开始出现。另外，时间速度的超级折算在50次就开始出现。',
    'Reward: Super Rank starts later, Super Tickspeed scales weaker based on completions.': '奖励：使级别的超级折算延迟出现，时间速度的超级折算效果基于完成次数而弱化。',
    'Reward: Supercritical Rank & All Fermions Tier scaling starts later, Super Overpower scales weaker based on completions.': '奖励：使级别和所有费米子的超临界折算延迟出现，降伏器的超级折算效果基于完成次数而弱化。',
    'You cannot buy Tickspeed.': '您无法购买时间速度。',
    'Reward: Each completion adds +7.5% to Tickspeed Power.': '奖励：每次完成该挑战，就使时间速度倍率增加7.5%。',
    'Mass gain softcap starts 150 OoMs eariler, and is stronger.': '质量获取速度软上限提前150个数量级出现，且效果变得更严重。',
    'Reward: Mass gain is raised based on completions (doesn\'t apply in this challenge).': '奖励：使质量获取速度随着完成次数变为原来的一个指数(在该挑战内此奖励无效)。',
    'Rage Power gain is rooted by 10. Additionally, mass gain softcap starts 100 OoMs eariler.': '狂怒能量获取速度变为原来的十次方根。另外，质量获取速度软上限提前100个数量级出现.',
    'Reward: Rage Powers gain is raised by completions.': '奖励：使狂怒能量获取速度随着完成次数变为原来的一个指数。',
    'You cannot rank up.': '您无法提升级别。',
    'Reward: Rank requirement is weaker based on completions.': '奖励：使级别的需求基于完成次数而降低。',
    'Reward: Exotic Rank & Tier, Ultra Prestige Level scale weaker based on completions.': '奖励：使级别和阶层的奇异折算和转生等级的超究折算基于完成次数而弱化。',
    'You cannot buy Tickspeed or BH Condenser.': '您无法购买时间速度和黑洞压缩器。',
    'Reward: Every completion adds 10% to tickspeed and BH condenser power.': '奖励：每次完成该挑战，就使时间速度倍率和黑洞压缩器倍率增加10%。',
    'You cannot gain rage powers. Instead, dark matters are gained from mass at a reduced rate. Additionally, mass gain softcap is stronger.': '您无法获得狂怒能量，但暗物质可以通过质量，而不是狂怒能量来获取，只是获取倍率降低。另外，质量获取速度软上限的效果变得更严重。',
    'Reward: Each completion increases challenges 1-4 cap by 2.': '奖励：每次完成该挑战，就使挑战1-挑战4的次数上限增加2。',
    'Reward: Pre-Impossible challenges scale weaker by completions, but this reward doesn\'t affect C7.': '奖励：使无望之前的挑战折算随着完成次数而弱化，但对挑战7无效。',
    'On 16th completion, unlock Elements': '第16次完成该挑战时，解锁元素',
    'Dark Matter & Mass from Black Hole gains are rooted by 8.': '暗物质和黑洞质量变为原来的八次方根。',
    'Reward: Dark Matter & Mass from Black Hole gains are raised by completions.': '奖励：使暗物质和黑洞质量获取速度随着完成次数变为原来的一个指数。',
    'On first completion, unlock 3 rows of Elements': '第1次完成该挑战时，解锁3行元素',
    'You cannot assign quarks. Additionally, mass gains exponent is raised to 0.9th power.': '您无法分配夸克。另外，质量获取速度的指数变为原来的0.9次方。',
    'Reward: Improve Magnesium-12.': '奖励：使镁(12Mg)的效果变得更好。',
    'You are trapped in mass dilation and challenges 1-8.': '强制进行质量膨胀，挑战1-挑战8同时触发。',
    'Reward: The exponent of the RP formula is multiplied by completions. (this effect doesn\'t work while in this challenge': '奖励：使相对论粒子公式的指数乘以该挑战的完成次数。(在该挑战内此奖励无效',
    'On first completion, unlock Fermions!': '第1次完成该挑战时，解锁费米子！',
    'You cannot gain dilated mass, and you are stuck in mass dilation.': '您无法获得相对论粒子和膨胀质量。强制进行质量膨胀。',
    'Reward: Star boosters are stronger based on completions.': '奖励：使星辰发生器的效果随着完成次数变得更好。',
    'You cannot gain Atoms or Quarks.': '您无法获得原子和夸克。',
    'Reward: Completions add free Radiation Boosters.': '奖励：每次完成该挑战，就获得免费的辐射波升级。',
    'On first completion, unlock new prestige layer!': '第1次完成该挑战时，解锁新的转生层级！',
    'Normal mass and mass of black hole gains are set to lg(x)^^1.5.': '质量和黑洞质量变为原来的lg(x)^^1.5。',
    'Reward: Increase dark ray earned based on completions.': '奖励：使暗射线获取速度随着完成次数增加。',
    'On first completion, unlock more features!': '第1次完成该挑战时，解锁更多内容！',
    'You cannot purchase any pre-118 elements. Additionally, you are trapped in quantum challenge with modifiers [5,5,5,5,5,5,5,5].': '您无法购买118号元素之前的任何元素。另外，您强制以[5,5,5,5,5,5,5,5]的配置进行量子挑战。',
    'Reward: Gain more primordium theorems.': '奖励：增加原基定理的获取速度。',
    'You are trapped in c1-12 and quantum challenge with modifiers [10,5,10,10,10,10,10,10].': '挑战1-挑战12同时触发。另外，您强制以[10,5,10,10,10,10,10,10]的配置进行量子挑战。',
    'Reward: Normal mass\'s overflow starts later based on completions.': '奖励：使质量的溢出基于完成次数而延迟出现。',
    '• You cannot gain rage powers, and all matters\' formulas are disabled, and they generate each other. Red matter generates dark matter.': '• 您无法获得狂怒能量，所有物质的公式都被禁用，它们会互相产生彼此。红色物质可以产生暗物质。',
    '• Pre-C16 features, such as rank, prestige tiers, main upgrades, elements, tree upgrades, etc. may be corrupted (disabled).': '• 挑战16之前的一些内容，例如级别、转生、主要升级、元素、中子树等可能受到腐化(即效果禁用)。',
    '• You are trapped in Mass Dilation & Dark Run with 100 all glyphs (10 slovak glyphs).': '• 您强制进行质量膨胀和黑暗狂奔，所有雕文(除了斯洛伐克雕文为10)为100。',
    '• Primordium particles are disabled.': '• 原基定理被禁用。',
    '• Pre-Quantum global speed is always set to /100.': '• 量子之前所有资源获取速度常时为/100。',
    'You can earn Corrupted Shards based on your mass of black hole, when exiting the challenge.': '您可以根据退出挑战时的黑洞质量获得腐化碎片。',
    'Reward: Improve Hybridized Uran-Astatine.': '奖励：使铀砹混合物的效果变得更好。',
    'On first completion, unlock ???': '第1次完成该挑战时，解锁？？？',
    '[Corrupted]': '[已腐化]',
    'Entering this challenge will force dark matter reset.': '进入挑战时将强制进行暗物质重置。',
    'Entering this challenge will force atom reset.': '进入挑战时将强制进行原子重置。',
    'Entering challenge will supernova reset.': '进入挑战时将同时在未前往超新星的前提下重置！',
    'Entering challenge will force a Darkness reset.': '进入挑战时将强制融入黑暗！',
    'Entering challenge will force an FSS reset.': '进入挑战时将强制进行最终星辰碎片重置。',
    ' Quantum Shard. Each Quantum Shard multiply Quantum Foams gained by ': '量子碎片。每量子碎片可以使量子泡沫获取速度乘以',
    'Which translates to a ': '相当于使量子泡沫获取速度变为原来的',
    'x multiplier to Quantum Foams.': '倍',
    'Enter the Quantum Challenge': '进入量子挑战',
    'Exit the Quantum Challenge': '退出量子挑战',
    'Modifications': '挑战限制',
    'Presets': '挑战预设',
    'Note 1: Hover any image to show challenge description': '提示1：鼠标停留在图片上方可以查看挑战详情。',
    'Note 2: While in Quantum Challenge, you need to go Quantum to complete the Quantum Challenge': '提示2：在量子挑战中，您需要前往量子才能完成它。',
    'Add present as your modifications': '将目前的挑战限制设置为挑战预设',
    'You cannot add QC Preset because of maxmium length of presets': '预设数量已达上限，无法再增加新预设',
    'New Preset': '新预设',
    'Preset Saved': '预设已保存',
    'Preset Loaded to Modifiers': '预设已载入至挑战限制',
    'Preset Renamed': '预设已重命名',
    'Preset Deleted': '预设已删除',
    'Load': '载入',
    'Rename': '重命名',
    'Delete': '删除',
    //#endregion
    //#region 原子
    ' unassigned Quarks': '尚未分配的夸克',
    'Distribute': '分配',
    'Ratio Mode': '比例模式',
    'Assign': '分配',
    ' Protons': '质子',
    ' Neutrons': '中子',
    ' Electrons': '电子',
    'Which generates ': '它可以产生',
    ' Protons Powers': '质子能量',
    ' Neutrons Powers': '中子能量',
    ' Electrons Powers': '电子能量',
    'Because of quark overflow at ': '因为夸克超过了',
    ', your quark gain is raised by ': '，发生溢出，因此它变为了以下次方：',
    ', your quark gain is rooted by ': '，发生溢出，因此它变为了以下次方根：',
    '[Hydrogen]': '[氢]',
    '[Helium]': '[氦]',
    '[Lithium]': '[锂]',
    '[Beryllium]': '[铍]',
    '[Boron]': '[硼]',
    '[Carbon]': '[碳]',
    '[Nitrogen]': '[氮]',
    '[Oxygen]': '[氧]',
    '[Fluorine]': '[氟]',
    '[Neon]': '[氖]',
    '[Sodium]': '[钠]',
    '[Magnesium]': '[镁]',
    '[Aluminium]': '[铝]',
    '[Silicon]': '[硅]',
    '[Phosphorus]': '[磷]',
    '[Sulfur]': '[硫]',
    '[Chlorine]': '[氯]',
    '[Argon]': '[氩]',
    '[Potassium]': '[钾]',
    '[Calcium]': '[钙]',
    '[Scandium]': '[钪]',
    '[Titanium]': '[钛]',
    '[Vanadium]': '[钒]',
    '[Chromium]': '[铬]',
    '[Manganese]': '[锰]',
    '[Iron]': '[铁]',
    '[Cobalt]': '[钴]',
    '[Nickel]': '[镍]',
    '[Copper]': '[铜]',
    '[Zinc]': '[锌]',
    '[Gallium]': '[镓]',
    '[Germanium]': '[锗]',
    '[Arsenic]': '[砷]',
    '[Selenium]': '[硒]',
    '[Bromine]': '[溴]',
    '[Krypton]': '[氪]',
    '[Rubidium]': '[铷]',
    '[Strontium]': '[锶]',
    '[Yttrium]': '[钇]',
    '[Zirconium]': '[锆]',
    '[Niobium]': '[铌]',
    '[Molybdenum]': '[钼]',
    '[Technetium]': '[锝]',
    '[Ruthenium]': '[钌]',
    '[Rhodium]': '[铑]',
    '[Palladium]': '[钯]',
    '[Silver]': '[银]',
    '[Cadmium]': '[镉]',
    '[Indium]': '[铟]',
    '[Tin]': '[锡]',
    '[Antimony]': '[锑]',
    '[Tellurium]': '[碲]',
    '[Iodine]': '[碘]',
    '[Xenon]': '[氙]',
    '[Caesium]': '[铯]',
    '[Barium]': '[钡]',
    '[Lanthanum]': '[镧]',
    '[Cerium]': '[铈]',
    '[Praseodymium]': '[镨]',
    '[Neodymium]': '[钕]',
    '[Promethium]': '[钷]',
    '[Samarium]': '[钐]',
    '[Europium]': '[铕]',
    '[Gadolinium]': '[钆]',
    '[Terbium]': '[铽]',
    '[Dysprosium]': '[镝]',
    '[Holmium]': '[钬]',
    '[Erbium]': '[铒]',
    '[Thulium]': '[铥]',
    '[Ytterbium]': '[镱]',
    '[Lutetium]': '[镥]',
    '[Hafnium]': '[铪]',
    '[Tantalum]': '[钽]',
    '[Tungsten]': '[钨]',
    '[Rhenium]': '[铼]',
    '[Osmium]': '[锇]',
    '[Iridium]': '[铱]',
    '[Platinum]': '[铂]',
    '[Gold]': '[金]',
    '[Mercury]': '[汞]',
    '[Thallium]': '[铊]',
    '[Lead]': '[铅]',
    '[Bismuth]': '[铋]',
    '[Polonium]': '[钋]',
    '[Astatine]': '[砹]',
    '[Radon]': '[氡]',
    '[Francium]': '[钫]',
    '[Radium]': '[镭]',
    '[Actinium]': '[锕]',
    '[Thorium]': '[钍]',
    '[Protactinium]': '[镤]',
    '[Uranium]': '[铀]',
    '[Neptunium]': '[镎]',
    '[Plutonium]': '[钚]',
    '[Americium]': '[镅]',
    '[Curium]': '[锔]',
    '[Berkelium]': '[锫]',
    '[Californium]': '[锎]',
    '[Einsteinium]': '[锿]',
    '[Fermium]': '[镄]',
    '[Mendelevium]': '[钔]',
    '[Nobelium]': '[锘]',
    '[Lawrencium]': '[铹]',
    '[Rutherfordium]': '[𬬻]',
    '[Dubnium]': '[𬭊]',
    '[Seaborgium]': '[𬭳]',
    '[Bohrium]': '[𬭛]',
    '[Hassium]': '[𬭶]',
    '[Meitnerium]': '[䥑]',
    '[Darmstadium]': '[𫟼]',
    '[Roeritgenium]': '[𬬭]',
    '[Copernicium]': '[鎶]',
    '[Nihonium]': '[鉨]',
    '[Flerovium]': '[𫓧]',
    '[Moscovium]': '[镆]',
    '[Livermorium]': '[鉝]',
    '[Tennessine]': '[石田]',
    '[Oganesson]': '[气奥]',
    '[Muonic Hydrogen]': '[μ子-氢]',
    '[Muonic Helium]': '[μ子-氦]',
    '[Muonic Lithium]': '[μ子-锂]',
    '[Muonic Beryllium]': '[μ子-铍]',
    '[Muonic Boron]': '[μ子-硼]',
    '[Muonic Carbon]': '[μ子-碳]',
    '[Muonic Nitrogen]': '[μ子-氮]',
    '[Muonic Oxygen]': '[μ子-氧]',
    '[Muonic Fluorine]': '[μ子-氟]',
    '[Muonic Neon]': '[μ子-氖]',
    '[Muonic Sodium]': '[μ子-钠]',
    '[Muonic Magnesium]': '[μ子-镁]',
    '[Muonic Aluminium]': '[μ子-铝]',
    '[Muonic Silicon]': '[μ子-硅]',
    '[Muonic Phosphorus]': '[μ子-磷]',
    '[Muonic Sulfur]': '[μ子-硫]',
    '[Muonic Chlorine]': '[μ子-氯]',
    '[Muonic Argon]': '[μ子-氩]',
    'Quark gain formula is better.': '使增加夸克获取速度的公式变得更好。',
    'Hardened Challenge scaling is 25% weaker.': '使硬化挑战的折算效果弱化25%。',
    'Electron Powers boost Atomic Powers gain.': '使电子能量可以加成原子能量获取速度。',
    'Stronger\'s power is stronger based on Proton Powers.': '使强化器倍率基于质子能量变得更多。',
    'The 7th challenge\'s effect is twice as effective.': '使挑战7的奖励效果翻倍。',
    'Gain 1% more quarks for each challenge completion.': '每完成1次任意挑战，夸克获取速度就增加1%。',
    'Carbon\'s effect is now multiplied by the number of elements bought.': '使碳(6C)的效果乘以已经购买的元素数量。',
    'C2\'s reward\'s softcap is 75% weaker.': '使挑战2的奖励软上限弱化75%。',
    'Tetr\'s requirement is 15% weaker.': '使四重阶层的需求降低15%。',
    'Nitrogen\'s multiplier is squared.': '使氮(7N)的效果变为原来的平方。',
    'Power\'s gain from each particle formula is better.': '使所有粒子的能量获取公式变得更好。',
    'For every c7 completion, increase c5 and c6 cap by 2.': '每完成1次挑战7，就使挑战5和挑战6的次数上限增加2。',
    'Passively gain 5% of the quarks you would get from resetting each second.': '每秒获得夸克，数量为重置时获取数量的5%。',
    'Super BH Condenser & Cosmic Ray scale 20% weaker.': '使黑洞压缩器和宇宙射线的超级折算弱化20%。',
    'Silicon\'s effect is +2% better for each element bought.': '每购买1种元素，就使硅(14Si)的效果数值增加2%。',
    'Raise Atom gain by 1.1.': '使原子的获取速度变为原来的1.1次方。',
    'You can now automatically buy Cosmic Rays. Cosmic Ray raises tickspeed effect at an extremely reduced rate.': '您可以自动购买宇宙射线。使宇宙射线可以增加时间速度效果，只是效果倍率极度降低。',
    '2nd Neutron\'s effect is better.': '使中子的第2个效果变得更好。',
    'Increase C7 cap by 50.': '使挑战7的次数上限增加50。',
    'Unlock Mass Dilation.': '解锁质量膨胀。',
    'Dilated mass gain is increased by tickspeed at a reduced rate.': '使时间速度可以加成膨胀质量获取速度，只是效果倍率降低。',
    'Atomic power\'s effects are better.': '使原子能量的效果变得更好。',
    'Passively gain 100% of the atoms you would get from resetting each second. Atomic Power boost Relativistic particles gain at a reduced rate.': '每秒获得原子，数量为重置时获取数量的100%。使原子能量可以加成相对论粒子获取速度，只是效果倍率降低。',
    'Increases Mass Dilation upgrade 1\'s base by 1.': '使质量膨胀升级1的基础效果增加1倍。',
    'Hardened challenge scaling is weaker for each element bought.': '使硬化挑战的折算效果基于购买的元素数量而弱化。',
    'Hyper/Ultra Rank & Tickspeed scales 25% weaker.': '使级别和时间速度的究极折算和超究折算弱化25%。',
    'Mass gain is raised to 1.5 while in mass dilation.': '在质量膨胀中，使质量获取速度变为原来的1.5次方。',
    'Proton power\'s effects are better.': '使质子能量的效果变得更好。',
    'Electron power\'s effects are better. Passively gain 10% of each particle you would assign quarks.': '使电子能量的效果变得更好。自动获得每种粒子，数量为分配夸克时增加数量的10%。',
    'Dilated mass boosts Relativistic particles gain.': '使膨胀质量可以加成相对论粒子获取速度。',
    'Increase dilated mass gain exponent by 5%.': '使膨胀质量获取速度的指数增加5%。',
    'Add 50 more C8 maximum completions.': '使挑战8的次数上限增加50。',
    'Rage power boosts Relativistic particles gain.': '使狂怒能量可以加成相对论粒子获取速度。',
    'Mass from Black Hole boosts dilated mass gain.': '使黑洞质量可以加成膨胀质量获取速度。',
    'Unlock Stars.': '解锁星辰。',
    'Super Tier scales weaker based on Tetr.': '使阶层的超级折算基于四重阶层的数值而弱化。',
    'Cosmic Ray\'s free tickspeeds now add to RU7.': '使通过宇宙射线获得的免费时间速度升级计入狂怒升级7。',
    'Remove softcap from C2 & C6 effects.': '移除挑战2和挑战6奖励效果的软上限。',
    'Collapsed star boosts dilated mass gain.': '使坍缩星辰可以加成膨胀质量获取速度。',
    'Add 50 more C7 maximum completions.': '使挑战7的次数上限增加50。',
    'Collapsed stars boost quark gain.': '使坍缩星辰可以加成夸克获取速度。',
    'You automatically buy mass dilation upgrades if you purchased them first. They no longer spend dilated mass.': '只要您购买过相应的质量膨胀升级，就可以自动购买它们。购买质量膨胀升级不再花费膨胀质量。',
    'The Tetr requirement is broken.': '使四重阶层的需求大幅降低。',
    'Collapsed star boosts relativistic particles gain.': '使坍缩星辰可以加成相对论粒子获取速度。',
    'Collapsed star\'s effect boosts mass of black hole gain at a reduced rate.': '使坍缩星辰可以加成黑洞质量获取速度，只是效果倍率降低。',
    'Quarks gain is raised to the 1.05th power.': '使夸克获取速度变为原来的1.05次方。',
    'Collapsed stars effect is 10% stronger.': '使坍缩星辰效果增加10%。',
    'Collapsed star boosts the last type of stars.': '使坍缩星辰可以加强最后一种星辰。',
    'Star generator is now ^1.05 stronger.': '使星辰发生器的速度变为原来的1.05次方。',
    'Mass gain softcap^2 is 10% weaker.': '使质量获取速度的二重软上限效果弱化10%。',
    'Mass of black hole boosts atomic powers gain at a reduced rate.': '使黑洞质量可以加成原子能量，只是效果倍率降低。',
    'Mass Dilation upgrade 6 is 75% stronger.': '使质量膨胀升级6的效果增加75%。',
    'Normal mass boosts all-star resources at a reduced rate.': '使质量可以加成所有星辰相关资源，只是效果倍率降低。',
    'Hyper/Ultra BH Condenser & Cosmic Ray scale 25% weaker.': '使黑洞压缩器和宇宙射线的究极和超究折算弱化25%。',
    'Add 200 more C8 maximum completions.': '使挑战8的次数上限增加200。',
    'Tickspeed power boosts base of Star Booster at a reduced rate.': '使时间速度倍率可以加成星辰发生器的基础加成，只是效果倍率降低。',
    'Ultra Rank & Tickspeed scale weaker based on Tier.': '使级别和时间速度的超究折算基于阶层的数值而弱化。',
    'The power from the mass of the BH formula is increased to 0.45.': '黑洞质量公式中，使指数增加为0.45。',
    'Add 100 more C7 maximum completions.': '使挑战7的次数上限增加100。',
    'Multiply Particle Powers gain by ^0.5 of its Particle\'s amount after softcap.': '使粒子能量的获取速度在到达软上限以后，乘以粒子数量的0.5次方。',
    'Ultra rank scaling starts 3 later for every supernova.': '每有一次前往超新星，级别的超究折算就延迟3次出现。',
    'Non-Bonus tickspeeds are 25x more effective.': '使非加成的时间速度效果变为原来的25倍。',
    'Rewards from Challenges 3, 4 & 8 are 50% more effective.': '使挑战3、挑战4和挑战8的奖励增加50%。',
    'Add 200 more C7 & C8 maximum completions.': '使挑战7和挑战8的次数上限增加200。',
    'Lanthanum\'s effect is twice as strong.': '使镧(57La)的效果翻倍。',
    'Collapsed stars boost quarks gain.': '使坍缩星辰可以加成夸克获取速度。',
    'Meta-Tickspeed starts 2x later.': '使时间速度的元折算延迟2倍出现。',
    'Pent is now added in mass gain formula from collapsed stars.': '使坍缩星辰的质量获取速度公式根据五重阶层的数值变得更好。',
    'Add 200 more C7 & C8 maximum completions.': '使挑战7和挑战8的次数上限增加200。',
    'BH formula softcap starts laster based on Supernovas.': '使黑洞质量获取公式的软上限基于超新星次数而延迟出现。',
    'Tetrs are 15% cheaper.': '使四重阶层的需求便宜15%。',
    'Add more C5-6 & C8 maximum completions based on Supernovas.': '使挑战5、挑战6和挑战8的次数上限基于超新星次数而增加。',
    'Super Tetr scales 25% weaker.': '使四重阶层的超级折算弱化25%。',
    'Remove 2 softcaps from Atomic Power\'s effect.': '移除原子能量效果的两重软上限。',
    'Collapsed Star\'s effect is 25% stronger.': '使坍缩星辰的效果增加25%。',
    'Mass softcap^3 is 17.5% weaker.': '使质量获取速度的三重软上限效果弱化17.5%。',
    'Meta-Supernova scales 20% weaker.': '使超新星的元折算弱化20%。',
    'Neutronium-0 affects Aluminium-13 & Tantalum-73.': '使零号中子的效果对铝(13Al)和钽(73Ta)也生效。',
    'Stronger & Tickspeed are 10x stronger.': '使强化器和时间速度的效果变为原来的10倍。',
    'Stronger is ^1.1 stronger.': '使强化器效果变为原来的1.1次方。',
    'Strontium-38 is thrice as effective.': '使锶(38Sr)的效果变为原来的3倍。',
    'Mass Dilation upgrade 2 effect is overpowered.': '使质量膨胀升级2的效果变得滥强。',
    'Pre-Ultra Mass Upgrades scale weaker based on Cosmic Ray\'s free tickspeeds.': '使超究折算之前的质量升级折算基于宇宙射线的免费时间速度升级数量而弱化。',
    'Stronger’s Power softcap starts 3x later, and is 10% weaker.': '使强化器倍率的软上限延迟3倍出现，且弱化10%。',
    'Tickspeed’s Power softcap starts ^2 later, and scales 50% weaker.': '使时间速度倍率的软上限延迟2次方出现，且折算弱化50%。',
    'Carbon-6’s effect is overpowered, but disable Sodium-11.': '使碳(6C)的效果变得滥强，但钠(11Na)失效。',
    'All tickspeed scalings start 100x later (after nerf from 8th QC modifier).': '使时间速度的所有折算延迟100倍出现(在计算量子挑战8的削弱之后生效)。',
    'Mass of Black Hole effect raises itself at a reduced logarithmic rate.': '使黑洞质量的效果基于自身数量的对数强化自身。',
    'Death Shard gain is boosted by Dilated Mass.': '使死寂碎片获取速度基于膨胀质量的数值而增加。',
    'Entropic Accelerator & Booster nerfing is 10% weaker.': '使熵加速和熵助推的削弱弱化10%。',
    'Insane Challenges scale 25% weaker.': '使挑战的疯狂折算弱化25%。',
    'Entropy gain is increased by 66.7% for every OoM^2 of normal mass.': '质量每有一个数量级的二次方，就使熵获取速度增加66.7%。',
    'Death Shard gain is increased by 10% for every supernova.': '每有一次前往超新星，死寂碎片获取速度就增加10%。',
    'Epsilon particles work in big rip, but are 90% weaker.': '使艾普西隆[E]粒子可以在大撕裂中生效，但弱化90%。',
    'Entropic Converter nerfing is 10% weaker.': '使熵转化的削弱弱化10%。',
    'Increase Entropic Evaporation’s base by 1.': '使熵消耗的基础效果增加1。',
    '8th QC modifier in Big Rip is 20% weaker.': '大撕裂中，使量子挑战8的削弱弱化20%。',
    'Remove softcap^3 from Photon Upgrade 3 effect, and its softcap^2 is weaker.': '移除光子升级3效果的三重软上限，并使它的二重软上限弱化。',
    'Prestige Base’s exponent is increased based on Pent.': '使转生基础值的指数基于五重阶层而增加。',
    'Blueprint Particles effect is overpowered.': '使蓝图粒子的效果变得滥强。',
    'Tickspeed Power’s softcap starts ^100 later.': '使时间速度倍率的软上限延迟100次方出现。',
    'Pre-Quantum Global Speed is more effective based on Honor.': '使量子之前所有资源获取速度基于荣耀数值而效果变得更好。',
    'Add 200 more C9-12 maximum completions.': '使挑战9-挑战12的次数上限增加200。',
    'Each Particle Power’s 1st effect is exponentially overpowered.': '使每种粒子能量的第一个效果变为指数加成。',
    'Entropic Evaporation^2 and Condenser^2 scale 15% weaker.': '使熵消耗²和熵压缩²的折算弱化15%。',
    'Beta Particles are twice as effective.': '使贝塔[B]粒子效果翻倍。',
    'All scalings from Ranks to Pent scale 10% weaker (only 2% during Big Rip).': '从级别到五重阶层的所有折算弱化10%(大撕裂时只弱化2%)。',
    'Entropic multiplier is effective in big rip.': '使熵加倍在大撕裂时也生效。',
    'Mass gain softcap^4 is 50% weaker (only 20% in Big Rip).': '使质量获取速度的四重软上限弱化50%(大撕裂时只弱化20%)。',
    'Neutron Stars raise Atom gain.': '使中子星可以加成原子获取速度。',
    '[sn4] effect is increased by 2.': '使[sn4]的效果增加2。',
    '[bs2] uses a better formula.': '使[bs2]的公式变得更好。',
    'Entropic Multiplier uses a better formula.': '使熵加倍的公式变得更好。',
    'Mass Dilation upgrades are 5% stronger.': '使质量膨胀升级的效果增加5%。',
    'Prestige Base boosts Relativistic Energy gain.': '使转生基础值可以加成相对论能量获取速度。',
    'Mass gain after all softcaps to ^5 is raised by 10.': '使五重之前所有软上限后的质量获取速度变为原来的10次方。',
    'Unlock ': '解锁',
    ', you\'ll able to go Dark.': '，您将可以融入黑暗。',
    'Pre-Quantum global speed affects dark shadow gain at a logarithmic reduced rate.': '使量子之前所有资源获取速度可以对黑暗之影获取速度生效，只是效果倍率以对数降低。',
    'Insane & Impossible Challenges scale 50% weaker.': '使挑战的疯狂和无望折算弱化50%。',
    'You can buy Cerium-58 in big rip.': '您可以在大撕裂中购买铈(58Ce)了。',
    'You can now automatically complete Challenges 9-11. Keep Challenge 12 completions on Big Rip or start QC.': '您可以自动完成挑战9-挑战11中的任意挑战。大撕裂或进入量子挑战时保留挑战12的完成次数。',
    'You can now automatically buy break dilation upgrades. They no longer spent relativistic mass.': '您可以自动购买撕裂膨胀升级。购买撕裂膨胀升级不再花费相对论质量。',
    'Keep quantum tree on darkness.': '融入黑暗时保留中子树的量子升级。',
    '7th challenge’s effect gives more C9-12 completions at 10% rate.': '使挑战7的奖励效果以10%的倍率增加挑战9-挑战12的次数上限。',
    'You can buy Tungsten-74 in Big Rip.': '您可以在大撕裂中购买钨(74W)了。',
    'Start with break dilation unlocked. Relativistic energy gain is increased by 10%.': '初始状态下就解锁撕裂膨胀。使相对论能量获取速度增加10%。',
    'You can buy atom upgrades 13-15 outside Big Rip.': '您可以在大撕裂外购买原子升级13-原子升级15了。',
    'Argon-18 is overpowered, it can affect BHC & Cosmic Ray powers.': '使氩(18Ar)的效果变得滥强，且可以对黑洞压缩器倍率和宇宙射线倍率生效。',
    'Entropic Scaling & Radiation work in Big Rip.': '使熵折算和熵辐射可以在大撕裂中生效。',
    'You can now automatically complete Challenge 12.': '您可以自动完成挑战12。',
    'Unlock the 13th Challenge, Automate Big Rip upgrades.': '解锁挑战13。您可以自动购买大撕裂升级。',
    'Make the 3rd, 4th & 8th Challenges’ effect better.': '使挑战3、挑战4和挑战8的奖励效果变得更好。',
    'Super Prestige Level & Honor are 5% weaker.': '使转生等级和荣耀的超级折算弱化5%。',
    'Dark Shadow gain is boosted by Death Shards.': '使黑暗之影获取速度基于死寂碎片的数值而增加。',
    'You can now gain Relativistic Energy outside of Big Rip. Keep non-QoL quantum tree on entering any dark challenge.': '您可以在大撕裂外获得相对论能量了。进入黑暗挑战时可以保留中子树量子后解锁升级中的非QoL升级。',
    'Super & Hyper cosmic string scalings are 25% weaker.': '使宇宙弦的超级折算和究极折算弱化25%。',
    'Supernova boosts blueprint particles earned.': '使超新星次数可以加成蓝图粒子获取速度。',
    'Gain 100% of the Quantizes you would get from resetting each second. Supernova boosts quantizes.': '每秒获得前往量子次数，数量为重置时获取数量的100%。使超新星次数可以加成前往量子次数。',
    'Uncap 10th Quantize milestone’s effect.': '移除量子里程碑中前往量子10次的效果上限。',
    'Gain 10x more dark rays.': '使暗射线获取速度变为10倍。',
    'Uncap Strange & Neutrino.': '移除[奇夸克]和[中微子]的阶层上限。',
    'Dark shadow’s second effect is better. Keep pre-118 big rip elements on darkness.': '使黑暗之影的第二个效果变得更好。融入黑暗时可以保留118号元素之前需进入大撕裂才能获取的元素。',
    'Unlock the 14th Challenge.': '解锁挑战14。',
    'Prestige Base boosts dark rays earned.': '使转生基础值可以加成暗射线获取速度。',
    'Quantum shard’s base is increased based on the number of elements bought.': '使量子碎片的基础效果指数基于购买的元素数量而增加。',
    'Outside of Big Rip, you can now gain Death Shards. Automate Cosmic Strings.': '您可以在大撕裂外获得死寂碎片了。您可以自动购买宇宙弦。',
    'Big Rip upgrade 7 is active outside of Big Rip.': '使大撕裂升级7在大撕裂外也生效。',
    'Stronger’s effect softcap is slightly weaker.': '使强化器效果的软上限略微弱化。',
    'Stronger’s effect softcap is slightly weaker again. Tickspeed’s effect is overpowered.': '使强化器效果的软上限再度略微弱化。使时间速度效果变得滥强。',
    'Add 75 more C13 maximum completions.': '使挑战13的次数上限增加75。',
    'Boost Dark Ray gain based on quarks.': '使暗射线获取速度基于夸克的数值而增加。',
    'Prestige base exponent boosts Abyssal Blot gain.': '使转生基础值的指数可以加成深渊之渍获取速度。',
    'Hyper Prestige Level, Tetr & Pent scalings are 10% weaker.': '使转生等级、四重阶层和五重阶层的究极折算弱化10%。',
    'Meta-Rank Boost affects Meta-Tier starting at a reduced rate.': '使级别元折算加成可以延迟阶层的元折算，只是效果倍率降低。',
    'Uncap Top & Neut-Muon.': '移除[顶夸克]和[缪中微子]的阶层上限。',
    'Uncap [Neut-Muon]’s effect, and it’s better if its effect is greater than 33%.': '移除[缪中微子]的效果上限，如果它的效果超过33%，还会使它的效果变得更好。',
    'Meta-Tickspeed scaling starts ^2 later.': '使时间速度的元折算延迟2次方出现。',
    'Abyssal Blot’s second effect applies to mass gain’s softcap^7-8, they are 20% weaker.': '使深渊之渍的第二个效果也对质量获取速度的七重软上限和八重软上限生效，且使它们弱化20%。',
    'Stronger Power’s softcap is weaker.': '使强化器倍率的软上限弱化。',
    'Unlock Dark Run. Keep Oganesson-118 on darkness.': '解锁黑暗狂奔。融入黑暗时可以保留气奥(118Og).',
    'Collapsed star’s effect now provide an exponential boost at a reduced rate. It now applies to mass of black hole gain. But nullify Palladium-46, Cadmium-48, Thulium-69 & Osmium-76.': '使坍缩星辰的效果变为指数加成，但效果倍率降低。它可以对黑洞质量获取速度生效。使钯(46Pd)、镉(48Cd)、铥(69Tm)和锇(76Os)失效。',
    'Spatial Dilation is slightly weaker.': '使空间膨胀(量子挑战7)略微弱化。',
    '[m1]’s effect is overpowered.': '使[m1]的效果变得滥强。',
    '[rp1]’s effect is overpowered again.': '使[rp1]的效果也变得滥强。',
    '[bh1]’s effect is overpowered for the third time.': '使[bh1]的效果也变得滥强。',
    'Hex’s requirement and Glory’s requirement are slightly weaker.': '使六重阶层和赞颂的需求略微降低。',
    'Unlock the 15th Challenge.': '解锁挑战15。',
    'Remove two softcaps of particle powers gain.': '移除粒子能量的两重软上限。',
    'Collapsed star’s effect is even better.': '使坍缩星辰的效果变得更好。',
    'Add 100 more C13-C14 maximum completions.': '使挑战13和挑战14的次数上限增加100。',
    'Uncap bonus fermions from Epsilon Particles.': '移除艾普西隆粒子的费米子阶层加成上限。',
    'Uncap Bottom.': '移除[底夸克]的阶层上限。',
    'Neutronium-0 can affect supernova challenges at a reduced rate.': '使零号中子的效果可以对挑战9-挑战12生效，只是效果倍率降低。',
    'Super & Hyper prestige levels start +30 later.': '使转生等级的超级折算和究极折算延迟30次出现。',
    'Supernova boosts dark rays earned.': '使超新星次数可以加成暗射线获取速度。',
    'Dark Shadow’s fifth effect also boosts entropy cap at a reduced rate.': '使黑暗之影的第五个效果可以加成熵上限，只是效果倍率降低。',
    'Exotic rank starts later based on meta-rank starting.': '使级别的奇异折算基于级别的元折算数值而延迟出现。',
    'Entropy\'s cap is increased by 25% every prestige level. Entropic Evaporation^2 is slightly weaker.': '转生等级每有一级，就使熵上限增加25%。使熵消耗²的折算略微弱化。',
    'Reduce first 12 challenges’ scaling’s strength by 30%.': '使前12个挑战的折算弱化30%。',
    'Meta-Tier starts x10 later.': '使阶层的元折算延迟10倍出现。',
    'Raise collapsed stars gain after softcap by 10.': '使坍缩星辰获取速度在计算软上限的削弱之后变为原来的10次方。',
    'Entropy boosts dark ray gain.': '使熵可以加成暗射线获取速度。',
    'Super Pent & Hex start later based on Hybridized Uran-Astatine\'s first effect.': '五重阶层和六重阶层的超级折算基于铀砹混合物的第一个效果延迟出现。',
    'Entropy’s hardcap is now a softcap.': '使熵上限的硬上限变为软上限。',
    'Add 100 more C13-C15 maximum completions.': '使挑战13-挑战15的次数上限增加100。',
    'Black hole overflow starts later based on prestige base.': '使黑洞的溢出基于转生基础值而延迟出现。',
    'Unlock The Matters.': '解锁物质。',
    'Dark matter boosts abyssal blots gain. Ultra mass upgrades start ^1.5 later.': '使暗物质可以加成深渊之渍获取速度。使质量升级的超究折算延迟1.5次方出现。',
    'Chromas gain is raised to 1.1th power.': '使色度获取速度变为原来的1.1次方。',
    'Z0 Boson’s first effect raises tickspeed power at a reduced rate.': '使Z0玻色子的第一个效果可以加成时间速度倍率，只是效果倍率降低。',
    'Each Matter’s gain is increased by 10% for every OoM^2 of Dark Matter. Unlock more main upgrades.': '暗物质每有一个数量级的二次方，就使每种物质的获取速度增加10%。解锁更多主要升级。',
    'Hybridized Uran-Astatine’s first effect makes Exotic Rank and Meta-Tier start later at ^0.5 rate.': '使铀砹混合物的第一个效果可以对奇异折算和元折算生效，只是效果倍率变为原来的0.5次方。',
    'Keep prestige tiers on darkness. Super and Hyper Prestige Levels start x2 later.': '融入黑暗时保留转生的相关等级阶层。使转生等级的超级折算和究极折算延迟2倍出现。',
    'Fermium-100 is slightly stronger. Automate each matter’s upgrade.': '使镄(100Fm)的效果略微增加。您可以自动购买每种物质的升级。',
    'Add 200 more C13-C14 maximum completions.': '使挑战13-挑战14的次数上限增加200。',
    'Exotic Rank and Ultra Prestige Level scaling are 10% weaker.': '使级别的奇异折算和转生等级的超究折算弱化10%。',
    'Particle powers’ first effect is better.': '使粒子能量的第一个效果变得更好。',
    'Unlock Accelerators, tickspeed now provides an exponential boost, but nullify Argon-18 and Unpentnilium-150 (except in 15th Challenge).': '解锁加速器，时间速度变为指数加成，但使氩(18Ar)和Unpentnilium(150Upn)的相应效果(除了挑战15以外的情况下)失效。',
    '15th challenge reward applies to black hole overflow.': '使挑战15的奖励效果可以对黑洞的溢出生效。',
    'Black hole’s effect provides an exponential boost to mass. Actinium-89 is now stronger outside big rip.': '使黑洞的效果对质量获取速度的加成变为指数加成。使锕(89Ac)在大撕裂外的效果变得更好。',
    'Unlock the fourth mass upgrade which raises Stronger.': '解锁第四个质量升级，它可以增加强化器倍率。',
    'Booster boosts its effect.': '使助推器可以对助推器效果生效。',
    '1st and 3rd Photon & Gluon upgrades provide an exponential boost. Keep big rip upgrades on darkness.': '使胶子和光子的第1、3个升级变为指数加成。融入黑暗时保留大撕裂升级。',
    'Overpower boosts accelerator power at a reduced rate.': '使降伏器可以加成加速器倍率，只是效果倍率降低。',
    'Dark matter boosts matter exponent.': '使暗物质可以加成物质的指数。',
    'Hybridized Uran-Astatine’s second effect applies to hex scalings. It is stronger.': '使铀砹混合物的第二个效果可以对六重阶层的折算生效，且它的效果变得更好。',
    'Unlock Beyond-Ranks.': '解锁超-级别。',
    'Muscler boosts its effect.': '使锻体器可以对锻体器效果生效。',
    'Stronger overflow starts later based on FSS.': '使强化器的溢出基于最终星辰碎片的数值而延迟出现。',
    'Meta-Rank Boost also affects Meta-Tetr starting at a reduced rate, strengthen Unpentpentium-155.': '使级别元折算加成可以延迟四重阶层的元折算，只是效果倍率降低。使Unpentpentium(155Upp)的效果变得更好。',
    'Exotic supernova scales 25% weaker.': '使超新星的奇异折算弱化25%。',
    '[Bottom]’s effect is now better, and is uncapped. Additionally, the Fourth Photon upgrade now provides an exponential boost.': '使[底夸克]的效果变得更好。使光子的第4个升级变为指数加成。',
    'Entropic Multiplier is overpowered.': '使熵加倍变得滥强。',
    'Entropic Evaporation^2 and Condenser^2 scale another 15% weaker.': '使熵消耗²和熵压缩²的折算再度弱化15%。',
    'Strengthen Unseptoctium-178 slightly.': '使Unseptoctium(178Uso)的效果略微增加。',
    'Final Star Shard\'s requirement is 20% cheaper.': '使最终星辰碎片的需求便宜20%。',
    'Unlock the 16th Challenge.': '解锁挑战16。',
    'Mass of unstable black hole boosts Pion gain.': '使不稳定黑洞质量可以加成π介子获取速度。',
    'Remove all pre-meta scalings from Fermion Tiers.': '移除费米子阶层所有元折算之前的折算。',
    'You can now automatically get all Meta-Fermions Tiers outside any Fermion.': '您可以自动获得元-费米子阶层。',
    '^1.1 to Matters gain inside C16, and ^1.05 to Matters\' exponent outside C16.': '在挑战16中使物质获取速度变为原来的1.1次方，在挑战16之外使物质的指数变为原来的1.05次方。',
    'Kaon & Pion are doubled every muonic element bought.': '每购买一个μ子元素，就使K介子和π介子的获取速度翻倍。',
    'Not affected by Neutronium-0, each pre-16 challenge’s completions boost each chroma gain.': '每完成1次挑战16之前的挑战，就可以使每种色度的获取速度增加，该效果不受零号中子影响。',
    'You can now automatically earn Cyrillic, Deutsch, and Swedish glyphs outside Dark Run, and they don’t affect dark run’s nerf.': '您可以自动获得西里尔雕文、德意志雕文、瑞典雕文，且它们不再影响黑暗狂奔的削弱。',
    'C9’s effect softcap is 1% weaker.': '使挑战9效果的软上限弱化1%。',
    'Remove the softcap of dark shadow’s fourth reward. Supernovas boost Pion gain': '移除黑暗之影第四项效果的软上限。使超新星次数可以加成π介子的获取速度。',
    'De-corrupt Unoctseptium-187.': '使Unoctseptium(187Uos)不再腐化。',
    'De-corrupt FSS’s reward to Matters.': '使最终星辰碎片对物质获取速度的加成不再腐化。',
    'Pion’s first reward is even stronger. Honor 247’s reward affects Pion gain.': '使π介子的第一个效果变得更强。使荣耀247的奖励也对π介子的获取速度生效。',
    'Pyro-Radioactive Plasma is better.': '使热放射性等离子体的效果变得更好。',
    'Final Star Shards increase Matter formula.': '使最终星辰碎片可以改良物质的公式。',
    'C15\'s reward affects mass overflow^2 starting.': '使挑战15的奖励效果也可以对质量的二重溢出生效。',
    'Dimensional mass affects pre-theorem\'s level.': '使维度质量可以影响所有定理的等级。',
    'Quantum times boost infinity points gain. De-nullify [Tau]’s effect, but its formula is changed.': '使前往量子次数可以加成无限点数获取速度。使[陶子]的重新生效，但公式发生变化。',
    'Accelerators raise the Argon-18\'s effect at an extremely reduced rate (after first overflow).': '使加速器可以加成氩(18Ar)的效果，只是效果倍率极度降低(在计算完第一重溢出之后生效)。',
    ' Relativistic particles': '相对论粒子',
    ' of dilated mass, which makes Tickspeed ': '膨胀质量，使时间速度增加',
    ' stronger': '',
    'inactive': '未激活',
    'Dilate Mass': '质量膨胀',
    'Double dilated mass gain.': '使膨胀质量获取速度翻倍。',
    'Make dilated mass effect stronger.': '使膨胀质量的效果变得更好。',
    'Double relativistic particles gain.': '使相对论粒子获取速度翻倍。',
    'Dilated mass also boost Stronger\'s power.': '使膨胀质量可以加成强化器倍率。',
    'Mass Dilation upgrade 3 scales 10% weaker.': '使质量膨胀升级3的折算弱化10%。',
    'Increase the exponent of the RP formula.': '增加相对论粒子公式的指数。',
    'Dilated mass boosts quark gain.': '使膨胀质量可以加成夸克获取速度。',
    'Mass Dilation upgrade 2 effect\'s formula is better.': '使质量膨胀升级2的效果公式变得更好。',
    'Tickspeed affects all-star resources at a reduced rate.': '使时间速度可以对所有星辰相关资源生效，只是效果倍率降低。',
    'Double quarks gain.': '使夸克获取速度翻倍。',
    'Add 0.015 to mass dilation upgrade 6\'s base.': '使质量膨胀升级6的基础效果增加0.015。',
    'First 3 Mass Dilation upgrades are stronger.': '使前3个质量膨胀升级的效果变得更好。',
    'Currently': '目前效果',
    ' of dilated mass gain will softcap dilated mass gain!': '的膨胀质量获取速度以后，膨胀质量获取速度将受到软上限限制！',
    'Because of dilated mass overflow at ': '因为膨胀质量超过了',
    ', your dilated mass is raised by ': '，发生溢出，因此它变为了以下次方：',
    ', your dilated mass is rooted by ': '，发生溢出，因此它变为了以下次方根：',
    ' Relativistic Energy': '相对论能量',
    ' of Relativistic mass': '相对论质量',
    'Fix Dilation': '修复膨胀',
    'Double Relativistic Mass gain.': '使相对论质量获取速度翻倍。',
    'Increase the exponent of the Dilated Mass formula.': '增加膨胀质量获取公式的指数。',
    'Multiplier from the DM effect is transformed to an exponent (at a reduced rate, is weaker while Big Ripped), but second MD upgrade\'s cost is exponentally increased. Purchasing this upgrade will reset it.': '使膨胀质量的效果变为对指数生效，只是效果倍率降低，进行大撕裂时效果更弱，但质量膨胀升级2的花费也变为指数型增长。购买此升级后将重置质量膨胀升级2的等级。',
    '11th MD upgrade is 50% stronger, its effective level softcaps at 1e18.': '使质量膨胀升级11的效果增加50%，有效等级的软上限变为1e18。',
    'Meta-Rank scales later.': '使级别的元折算延迟出现。',
    'Triple Relativistic Energy gain.': '使相对论能量获取速度变为原来的3倍。',
    'Death Shard & Entropy boost each other.': '使死寂碎片和熵互相加成彼此的获取速度。',
    'Relativistic Mass gain is increased by 75% for every OoM^2 of dilated mass.': '膨胀质量每有一个数量级的二次方，就使相对论质量获取速度增加75%。',
    'Pre-Quantum Global Speed affects Relativistic Mass gain at a severely reduced rate.': '使量子之前所有资源获取速度可以对相对论质量获取速度生效，只是效果倍率严重降低。',
    'Super Prestige Level starts 10 later.': '使转生等级的超级折算延迟10次出现。',
    'You can now automatically evaporate resources. (Stronger than manual).': '您可以自动消耗资源。(效果比手动更好)',
    'Double dark shadows gain.': '使黑暗之影获取速度翻倍。',
    'Muon-Catalyzed Fusion Tier ': 'μ子催化聚变阶层',
    ' Exotic Atoms (Based on Kaon & Pion).': '奇异原子(基于K介子和π介子数量)。',
    ' Kaons.': 'K介子。',
    ' Pions.': 'π介子。',
    'Boosts corrupted shard gain by ': '使腐化碎片获取速度变为原来的',
    'Ultra & Meta-Prestige Levels start ': '使转生等级的超究折算和元折算延迟',
    'Boosts entropy gain by ': '使熵获取速度变为原来的',
    'Impossible Challenges 1-12 start ': '使挑战1-挑战12的无望折算延迟',
    'Weaken softcaps of atomic power\'s effect by ': '使原子能量效果的软上限弱化',
    'Increase the base of Prestige Level 382 for Collapsed Star\'s effect, the base of Binilunium-201 for BH\'s effect by ': '使转生等级382对坍缩星辰效果的基础加成，以及Binilunium(201Bnu)对黑洞效果的基础加成增加',
    'Boosts mass of unstable BH gain by ': '使不稳定黑洞的获取速度变为原来的',
    'Black hole overflow starts ': '使黑洞的溢出延迟',
    'FSS\'s base is raised by ': '使最终星辰碎片基础值增加',
    'Cosmic String\'s power is raised by ': '使宇宙弦倍率增加',
    'Increase parallel extruder\'s power by ': '使平行挤出机倍率增加',
    //#endregion
    //#region 超新星
    'You have become SUPERNOVA!': '您终于成为了超新星！',
    'But will reset everything, and gain SUPERNOVA!': '迄今为止的一切都将重置，但可以获得超新星！',
    'You can pass it...': '继续前行吧……',
    '... to discover!': '去探索，去发现！',
    'You\'ll be Supernova...': '您将前往超新星……',
    'You become Supernova!': '您成为了超新星！',
    'You have ': '您拥有',
    ' Neutron star.': '中子星。',
    'Reset without being Supernova': '在未前往超新星的前提下重置',
    'Quality of life': '游戏体验',
    'Challenge': '挑战',
    'Post-Supernova': '超新星之后',
    'Start generating 0.1 Neutron Star per second (not affected by offline production).': '开始每秒产生0.1中子星(不受离线产量影响)。',
    'Tickspeed affects Neutron Star gain at a reduced rate.': '使时间速度可以加成中子星获取速度，只是效果倍率降低。',
    'Supernova boosts Neutron Star gain.': '使超新星次数可以加成中子星获取速度。',
    'Blue stars boost Neutron star gain at a reduced rate.': '使蓝色星辰可以加成中子星获取速度，只是效果倍率降低。',
    '[sn2]\'s effect base is increased by supernova.': '使中子树[sn2]的基础效果基于超新星次数而增加。',
    'Mass boosts Neutron Stars gain.': '使质量可以加成中子星获取速度。',
    'Neutron star multiplies Mass gain.': '使中子星可以加成质量获取速度。',
    'Raise the Mass requirement for softcap^2 by 1.5': '使质量获取速度的二重软上限阈值变为原来的1.5次方。',
    'Mass gain softcap^2-3 starts later based on Supernovas.': '使质量获取速度的二重软上限和三重软上限基于超新星次数而延迟出现。',
    'Tickspeed Power is raised to the 1.15th.': '使时间速度倍率变为原来的1.15次方。',
    'Neutron Stars multiplies Rage Powers gain': '使中子星可以加成狂怒能量获取速度。',
    'Neutron Star multiplies Dark Matters gain.': '使中子星可以加成暗物质获取速度。',
    'BH Condenser power is raised to the 1.15th.': '使黑洞压缩器倍率变为原来的1.15次方。',
    'Neutron Star boosts last star gain.': '使中子星可以加成最后一种星辰的获取速度。',
    'Tetr amount to Star boost’s softcap is 50% weaker.': '使星辰加成的四重阶层的软上限弱化50%。',
    'Star generators are stronger based on Supernova.': '使星辰发生器的效果基于超新星次数变得更强。',
    'After getting all 5 star types, star unlocker will transform into star boosters.': '解锁完所有5种星辰以后，星辰解锁的功能变为星辰加成。',
    'Start with Silicon-14 & Argon-18 unlocked. You can now automatically buy Elements & Atom upgrades.': '初始状态下就解锁硅(Si14)和氩(Ar18)。您可以自动购买元素和原子升级。',
    'Start with Chromium-24 and Atom upgrade 6 unlocked.': '初始状态下就解锁铬(Cr24)和原子升级6。',
    'Start with technetium-43 unlocked, and it\'s improved. You can automatically gain Relativistic particles from mass.': '初始状态下就解锁锝(Tc43)，且相应的元素效果变得更好。您可以自动从质量中获得相对论粒子。',
    'You can now automatically buy Star unlockers & boosters.': '您可以自动购买星辰解锁和星辰加成。',
    'Tetr no longer resets anything.': '四重阶层不再重置任何东西。',
    'While in any challenge, you can now automatically complete it before exiting.': '不需要退出挑战也可以自动完成它。',
    'You can now automatically buy Photon & Gluon upgrades, they no longer spent their amount.': '您可以自动购买光子和胶子升级，购买它们不再消耗相应资源。',
    'You can now automatically Pent up, Pent no longer resets anything.': '您可以自动提升五重阶层，五重阶层不再重置任何东西。',
    'You can now automatically buy Radiation Boosters, they no longer spent Radiation.': '您可以自动购买辐射波升级，购买它们不再消耗相应资源。',
    'Add 100 more C7 & C8 maximum completions.': '使挑战7和挑战8的次数上限增加100。',
    'Keep challenge 1-4 completions on reset.': '重置时保留挑战1-挑战4的完成次数。',
    'Keep challenge 5-8 completions on reset.': '重置时保留挑战5-挑战8的完成次数。',
    'Unlock the 9th Challenge.': '解锁挑战9。',
    'Challenge 9’s effect is better.': '使挑战9的奖励效果变得更好。',
    'Add 100 more C9 completions.': '使挑战9的次数上限增加100。',
    'Unlock the 10th Challenge.': '解锁挑战10。',
    'Unlock the 11th Challenge.': '解锁挑战11。',
    'Unlock the 12th Challenge.': '解锁挑战12。',
    'Challenge 12’s effect is better.': '使挑战12的奖励效果变得更好。',
    'Add 200 more C9-12 completions.': '使挑战9-挑战12的次数上限增加200。',
    'BH Condensers power boost Cosmic Rays power.': '使黑洞压缩器倍率可以加成宇宙射线倍率。',
    'Cosmic Rays Power is raised to 1.25th power.': '使宇宙射线倍率变为原来的1.25次方。',
    'Tickspeed affects Higgs Boson gain at a reduced rate.': '使时间速度可以加成希格斯玻色子获取速度，只是效果倍率降低。',
    'Photon, Gluon boosts each other\'s gain.': '使光子和胶子互相加成彼此的获取速度。',
    'Neutrons gain is affected by Graviton\'s effect at a reduced rate.': '使引力子可以加成中子获取速度，只是效果倍率降低。',
    'Raise Z Bosons gain to the 1.5th power.': '使Z玻色子获取速度变为原来的1.5次方。',
    'Z Bosons also affect BHC + CR powers.': '使Z玻色子可以加成黑洞压缩器倍率和宇宙射线倍率。',
    'Tickspeed affects Fermions gain at a reduced rate.': '使时间速度可以加成所有费米子获取速度，只是效果倍率降低。',
    'Unlock 2 more types of U-Quark & U-Fermion.': '再解锁两种U-夸克和U-轻子。',
    'Super fermion scaling is 7.5% weaker.': '使费米子阶层的超级折算弱化7.5%。',
    '2nd Photon & Gluon upgrades are slightly stronger.': '使光子和胶子升级2的效果略微增加。',
    '[Electron] max tier is increased by 35. Its effect softcap is weaker.': '使[电子]的阶层上限增加35，并使它的软上限效果弱化。',
    'Unlock 2 new final types of U-Quark & U-Fermion.': '解锁最后两种新的U-夸克和U-轻子。',
    'Unlock 2 final types of U-Quark & U-Fermion.': '解锁最后两种U-夸克和U-轻子。',
    '[Strange] & [Neutrino] max tier is increased by 2.': '使[奇夸克]和[中微子]的阶层上限增加2。',
    'Uncap [Electron] tier, its effect is overpowered.': '移除[电子]的阶层上限，使它的效果变得滥强。',
    '[Strange], [Top], [Bottom], [Neutrino], [Neut-Muon] max tiers are increased by 5.': '使[奇夸克]、[顶夸克]、[底夸克]、[中微子]和[缪中微子]的阶层上限增加5。',
    'Pre-meta fermion scalings are 10% weaker.': '使费米子阶层元折算之前的所有折算弱化10%。',
    'Generating Relativistic particles outside Mass dilation is 25% stronger.': '未进行质量膨胀时，使相对论粒子获取速度增加25%。',
    'Gain more frequency based on Supernova, it will also multiply Radiations that is not the last available types.': '使频率获取速度基于超新星次数而增加，并且使除了最后一种辐射波以外其他所有辐射波的波长获取速度增加。',
    'Gain 10x more all radiation types.': '使辐射波的波长获取速度变为原来的10倍。',
    'Radiation Boosts are 1.1x cheaper.': '使辐射波的加成便宜1.1倍。',
    'All Meta-Boosts are twice as effective.': '使所有元加成的效果翻倍。',
    'All Radiation gains are increased by 10% for every Supernova you have become.': '每有一次前往超新星，所有辐射波的波长获取速度就增加10%。',
    'Bonus radiation boosts are stronger based on radiation type.': '使每种辐射波获取速度的加成随着辐射波类型变得越来越强。',
    'Gain more Quantum Foams based on Supernovas.': '使量子泡沫获取速度基于超新星次数而增加。',
    'Quantum Foams are boosted by Neutron Stars.': '使中子星可以加成量子泡沫获取速度。',
    'Quantum Foams are boosted by Blueprint Particles.': '使蓝图粒子可以加成量子泡沫获取速度。',
    'Quantum Shard\'s base is increased by 0.5.': '使量子碎片的基础效果指数增加0.5。',
    'Good luck with the new era!': '祝您新时代好运！',
    'Fermion requirements are decreased by 20%.': '使费米子的需求减少20%。',
    'W+ Boson\'s 1st effect is overpowered.': '使W+玻色子的第一个效果变得滥强。',
    'BH formula\'s softcap is 30% weaker.': '使黑洞质量获取公式的软上限弱化30%。',
    'Remove softcaps from [sn2]\'s effect.': '移除[sn2]效果的软上限。',
    'Blueprint Particles & Chromas are affected by Tickspeed Effect at a reduced rate.': '使时间速度可以加成蓝图粒子和色度获取速度，只是效果倍率降低。',
    'Quantizes boost Cosmic string\'s power.': '使前往量子次数可以加成宇宙弦的倍率。',
    'Gain more Quantizes based on Quantum Shards.': '使前往量子次数基于量子碎片数量而增加。',
    'Chromas are affected by Quantum Shard’s effect.': '使量子碎片可以加成色度获取速度。',
    'Gain more Quantizes based on total Primordium Particles.': '使前往量子次数基于原基定理总数而增加。',
    'Higgs Boson\'s effect is increased by 3.3% for every OoM of Blueprint Particles.': '蓝图粒子每有一个数量级，就使希格斯玻色子的效果增加3.3%。',
    'Quantum Foams gain formula is better.': '使量子泡沫获取速度的公式变得更好。',
    'You now automatically purchase supernova tree upgrades as long as they don\'t cost quantum foam.': '您可以自动购买不需要量子泡沫的中子树升级。',
    'Keep U-Quark Tiers on going Quantum.': '前往量子时保留U-夸克的相关阶层。',
    'You can now automatically complete Challenges 1-4.': '您可以自动完成挑战1-挑战4。',
    'You can now automatically become a supernova, it no longer resets anything.': '您可以自动前往超新星，前往超新星不再重置任何东西。',
    'You can now automatically complete Challenges 5-8.': '您可以自动完成挑战5-挑战8。',
    'Keep U-Lepton Tiers on going Quantum.': '前往量子时保留U-轻子的相关阶层。',
    'Keep challenge 9-12 completions on going Quantum.': '前往量子时保留挑战9-挑战12的完成次数。',
    'You can now automatically get all Fermions Tiers outside any Fermion, except during Quantum Challenge.': '您可以自动获得费米子阶层，但在进行量子挑战时无效。',
    '[qu_qol8] now works in Quantum Challenge or Big Rip.': '使[qu_qol8]的效果在进行量子挑战或大撕裂时也生效。',
    'Start with Polonium–84 unlocked when entering in Quantum Challenge.': '进行量子挑战时，初始状态下就解锁钋(Po84)。',
    'Primordium Theorem’s base requirement is reduced by 1.': '原基定理的基础需求减少1。',
    'Theta Particle’s second effect is now added.': '西塔[Θ]粒子增加第二个效果。',
    'Epsilon Particle’s second effect is now added, stronger if you are in Quantum Challenge.': '艾普西隆[E]粒子增加第二个效果，在量子挑战中效果变得更好。',
    'Mass gain softcap^4 starts later based on Quantum Shards.': '使质量获取速度的四重软上限基于量子碎片数量而延迟出现。',
    'Get 1 extra shard when a nerf reaches 10.': '当一项挑战到达10时，可以额外获得1量子碎片。',
    'Quantum Shard\'s base is increased by Prestige Base.': '使量子碎片的基础效果指数基于转生基础值而增加。',
    'Evaporating frequency & mass of black hole is twice as effective, and its effects are stronger.': '消耗频率和黑洞质量的效率翻倍，且效果变得更好。',
    'Quantum Shards boost Death Shard gain.': '使量子碎片可以加成死寂碎片获取速度。',
    'Unlock Radiation.': '解锁辐射波。',
    'Unlock Primordium.': '解锁原基。',
    'Unlock Quantum Challenge.': '解锁量子挑战。',
    'Unlock Big Rip.': '解锁大撕裂。',
    'You can\'t gain Delta, Alpha, Omega & Sigma Particles from Primordium Theorem now. Instead, their amount is set to your total primordium theorems.': '您无法通过原基定理获得德尔塔、阿尔法、欧米伽和西格马粒子。但您可以根据原基定理的数值获得相同数值的相应粒子。',
    'You can\'t gain Phi & Epsilon Particles from Primordium Theorem now. Instead, their amount is set to your total primordium theorems.': '您无法通过原基定理获得斐和艾普西隆粒子。但您可以根据原基定理的数值获得相同数值的相应粒子。',
    'You can\'t gain Theta & Beta Particles from Primordium Theorem now. Instead, their amount is set to your total primordium theorems.': '您无法通过原基定理获得西塔和贝塔粒子。但您可以根据原基定理的数值获得相同数值的相应粒子。',
    'Unlock 2 meta-types of U-Quark & U-Fermion.': '解锁两种元类型的U-夸克和U-轻子。',
    'Best mass of black hole in C16 boosts normal mass gain.': '使挑战16中最高的黑洞质量可以加成质量获取速度。',
    'Best mass of black hole in C16 boosts bosonic resources gain.': '使挑战16中最高的黑洞质量可以加成玻色子获取速度。',
    'Best mass of black hole in C16 adds free fermion tiers.': '使挑战16中最高的黑洞质量可以额外增加费米子阶层。',
    'Best mass of black hole in C16 adds to the base of all matter\'s upgrade.': '使挑战16中最高的黑洞质量可以额外增加每种物质升级的基础值。',
    'Neutronium-0 now affects Challenge 13 at a reduced rate.': '使零号中子的效果对挑战13也生效，只是效果倍率降低。',
    'Mass overflow starts later based on best mass of black hole in C16.': '使质量的溢出基于挑战16中最高的黑洞质量的数值而延迟出现。',
    'Neutronium-0 now affects Challenge 14 at a reduced rate. (like [ct5]': '使零号中子的效果对挑战14也生效，只是效果倍率降低。(类似[ct5]的效果',
    'Keep pre-C16 tree on entering C16. Best mass of black hole in C16 boosts all radiation gains.': '进入挑战16时可以保留挑战16之前的中子树升级。使挑战16中最高的黑洞质量可以加成辐射波获取速度。',
    'Best mass of black hole in C16 adds free radiation boosts.': '使挑战16中最高的黑洞质量可以额外增加辐射波的免费升级。',
    'FSS Requirement is lower based on total corrupted shards.': '使最终星辰碎片的需求基于腐化碎片的总数而降低。',
    'Mass of black hole overflow starts later based on best mass of black hole in C16. (weaker during C16': '使黑洞质量的溢出基于挑战16中最高的黑洞质量而延迟出现。(在挑战16中效果弱化',
    'Best mass of black hole in C16 adds free primordium particles.': '使挑战16中最高的黑洞质量可以额外增加原基定理的免费升级。',
    'Neutronium-0 now affects Challenge 15 at a reduced rate (like [ct5]). C15 now affects Atomic & Quark Overflows.': '使零号中子的效果对挑战15也生效，只是效果倍率降低(类似[ct5]的效果)。挑战15的奖励对原子能量和夸克的溢出也生效。',
    'Dilated mass overflow starts later based on best mass of black hole in C16.': '使膨胀质量的溢出基于挑战16中最高的黑洞质量的数值而延迟出现。',
    'Total corrupted shards boost matters gain.': '使腐化碎片的总数可以加成物质获取速度。',
    'Best mass of black hole in C16 boosts Kaon & Pion gain.': '使挑战16中最高的黑洞质量可以加成K介子和π介子的获取速度。',
    'click any tree upgrade to show': '点击任意中子树升级以查看详情',
    'click again to buy if affordable': '如果资源足够，再次点击将购买升级',
    ' Graviton, which speed up Boson production by ': '引力子，因此玻色子获取速度乘以',
    ' Higgs Boson, which raise Graviton’s effect by ': '希格斯玻色子，因此引力子效果乘以',
    ' Photon': '光子',
    ' Gluon': '胶子',
    ' Boson, which multiply Mass gain by ': '玻色子，因此质量获取速度乘以',
    ' multiply W': '并使W',
    ' Boson gain by ': '玻色子获取速度乘以',
    ' Boson, which make Mass gain softcap^2 starts ^': '玻色子，因此质量获取速度的二重软上限延迟',
    ' later,': '次方出现，',
    ' Boson, which multiply Tickspeed Power by ': '玻色子，因此时间速度倍率乘以',
    ' multiply W Bosons gain by ': '并使W玻色子的获取速度乘以',
    'Note: Choosing any fermion will reset without being Supernova!': '注意：选择任意费米子后，将在未前往超新星的前提下重置！',
    'Back to Normal': '恢复正常',
    ' U-Quark': 'U-夸克',
    ' U-Lepton': 'U-轻子',
    '[Up]': '[上夸克]',
    '[Down]': '[下夸克]',
    '[Charm]': '[粲夸克]',
    '[Strange]': '[奇夸克]',
    '[Top]': '[顶夸克]',
    '[Bottom]': '[底夸克]',
    '[Meta-Quark]': '[元-夸克]',
    '[Electron]': '[电子]',
    '[Muon]': '[缪子]',
    '[Tau]': '[陶子]',
    '[Neutrino]': '[中微子]',
    '[Neut-Muon]': '[缪中微子]',
    '[Neut-Tau]': '[陶中微子]',
    '[Meta-Lepton]': '[元-轻子]',
    'Tier ': '阶层',
    'Next Tier at': '下一阶层需',
    '(Increased by Atomic Powers': '(单位为原子能量',
    '(Increased by Relativistic Particle': '(单位为相对论粒子',
    '(Increased by Mass': '(单位为质量',
    '(Increased by Rage Power': '(单位为狂怒能量',
    '(Increased by Dilated Mass': '(单位为膨胀质量',
    '(Increased by Tickspeed Effect': '(单位为时间速度效果',
    '(Increased by product of above u-quarks': '(单位为之前所有U-夸克之和',
    '(Increased by Quark': '(单位为夸克',
    '(Increased by Mass of Black Hole': '(单位为黑洞质量',
    '(Increased by Dark Matter': '(单位为暗物质',
    '(Increased by Collapsed Star': '(单位为坍缩星辰',
    '(Increased by Atom': '(单位为原子',
    '(Increased by Tickspeed Power': '(单位为时间速度倍率',
    '(Increased by product of above u-leptons': '(单位为之前所有U-轻子之和',
    'Effect': '效果',
    'On Active: ^0.6 to the exponent of Atomic Powers gain': '激活时，使原子能量的获取速度指数变为原来的0.6次方',
    'On Active: The exponent of the RP formula is divided by 10': '激活时，使相对论粒子公式的指数除以10',
    'On Active: You are trapped in Mass Dilation, and it is twice as strong': '激活时，强制进行质量膨胀，且惩罚翻倍',
    'On Active: You are trapped in Mass Dilation and Challenges 3-5': '激活时，强制进行质量膨胀，和挑战3-挑战5',
    'On Active: U-Quarks, Photons & Gluons do nothing': '激活时，使U-夸克，光子和胶子失效',
    'On Active: Challenges are disabled': '激活时，使挑战奖励失效',
    'On Active: All u-quarks at once, and force quantum reset.': '激活时，使之前所有U-夸克激活，并强制前往量子。',
    'On Active: ^0.625 to the exponent of Atoms gain': '激活时，使原子的获取速度指数变为原来的0.625次方',
    'On Active: The power from the mass of the BH formula is always -1': '激活时，黑洞质量公式中，使指数始终为-1',
    'On Active: You are trapped in Challenges 8-9': '激活时，强制进行挑战8和挑战9',
    'On Active: Star generators are decreased to ^0.5': '激活时，使星辰发生器的效果变为原来的0.5次方',
    'On Active: U-Leptons, Z': '激活时，使U-轻子，Z',
    ' bosons do nothing': '玻色子失效',
    'On Active: Radiation Boosts are disabled': '激活时，使辐射波加成失效',
    'On Active: All u-leptons at once, and force quantum reset.': '激活时，使之前所有U-轻子激活，并强制前往量子。',
    'Your frequency is ': '您的频率为',
    ' Hz, which multiples all Fermion gains by ': '赫兹，使费米子获取速度变为原来的',
    'At ': '当频率到达',
    ' of frequency, unlock ': '赫兹时，将解锁',
    ' meters.': '米。',
    ' meters': '米',
    ' Aplitude': '振幅',
    ' Velocity': '波速',
    'Radio Boost [': '无线电波加成[',
    'Tickspeed Boost [': '时间速度加成[',
    'Mass-Softcap Boost [': '质量软上限加成[',
    'Microwave Boost [': '微波加成[',
    'BH-Exponent Boost [': '黑洞指数加成[',
    'BH-Condenser Boost [': '黑洞压缩器加成[',
    'Infrared Boost [': '红外线加成[',
    'Photo-Gluon Boost [': '光子胶子加成[',
    'Meta-Boost I [': '元加成 I [',
    'Visible Boost [': '可见光加成[',
    'Cosmic-Ray Boost [': '宇宙射线加成[',
    'Neturon-Star Boost [': '中子星加成[',
    'Ultraviolet Boost [': '紫外线加成[',
    'Tickspeed-Softcap Boost [': '时间速度软上限加成[',
    'Meta-Rank Boost [': '级别元折算加成[',
    'X-ray Boost [': 'X射线加成[',
    'U-Lepton Boost [': 'U-轻子加成[',
    'Meta-Boost II [': '元加成 II [',
    'Gamma-ray Boost [': '伽马射线加成[',
    'U-Quark Boost [': 'U-夸克加成[',
    'BH-Exponent Boost II [': '黑洞指数加成 II [',
    ']: ': ']：',
    //#endregion
    //#region 量子
    ' Quantum Theory (based on every going quantum': '量子理论(基于前往量子次数',
    'Require Quantum Theory to start generating Pyro-Radioactive Plasma': '需要量子理论才可获得热放射性等离子体',
    'Require Quantum Theory to start generating Hybridized Uran-Astatine': '需要量子理论才可获得铀砹混合物',
    'Require Quantum Theory to start generating Neutronium-0': '需要量子理论才可获得零号中子',
    'Pyro-Radioactive Plasma': '热放射性等离子体',
    'Hybridized Uran-Astatine': '铀砹混合物',
    'Neutronium-0': '零号中子',
    ' Red Chroma, which': '红色色度，因此',
    ' Green Chroma, which': '绿色色度，因此',
    ' Blue Chroma, which': '蓝色色度，因此',
    'You Quantized ': '您已前往量子',
    ' times': '次',
    'Quantized ': '前往量子',
    'You start with qol1-6, bosons, and fermions unlocked.': '初始状态下就解锁qol1-qol6中子树升级、玻色子和费米子。',
    'Pre quantum supernova tree\'s requirements are gone. Pre-Quantum global speed is increased by 10x.': '使量子之前所有中子树升级不再需要满足前提条件。使量子之前所有资源获取速度变为原来的10倍。',
    'You start with challenges tree and qol7 unlocked.': '初始状态下就解锁与挑战有关的中子树升级，以及[qol7]中子树升级。',
    'You start with qol8-9, unl1, and radiation unlocked.': '初始状态下就解锁[qol8]、[qol9]和[unl1]中子树升级，以及辐射波。',
    'Double Quantum Foam gain.': '使量子泡沫获取速度翻倍。',
    'Pre-Quantum global speed affects Blueprint Particles and Chroma at a reduced rate.': '使量子之前所有资源获取速度可以加成蓝图粒子和色度获取速度，只是效果倍率降低。',
    'Supernova stars are boosted by Quantizes (capped at 1e10). Unlock Auto-Quantum.': '使前往量子次数可以加成超新星星辰(上限为1e10)。解锁自动前往量子。',
    'Auto-Quantum Mode': '自动前往量子模式',
    'Amount': '数量',
    'Time': '时间',
    ' Primordium Theorem (based on Blueprint Particles': '原基定理可供使用(基于蓝图粒子数量',
    '(+1 at ': '(下个需要',
    'Give 1 random Particle': '随机给予1个粒子',
    'Give 10 random Particles': '随机给予10个粒子',
    'Give all random Particles': '随机给予所有粒子',
    'Respec all Particles': '返还所有粒子',
    'Delta [Δ] Particles': '德尔塔[Δ]粒子',
    'Alpha [Α] Particles': '阿尔法[Α]粒子',
    'Omega [Ω] Particles': '欧米伽[Ω]粒子',
    'Sigma [Σ] Particles': '西格马[Σ]粒子',
    'Phi [Φ] Particles': '斐[Φ]粒子',
    'Epsilon [Ε] Particles': '艾普西隆[Ε]粒子',
    'Theta [Θ] Particles': '西塔[Θ]粒子',
    'Beta [Β] Particles': '贝塔[Β]粒子',
    ' Hz': '赫兹',
    'Evaporate your frequency to gain Enthalpy': '消耗频率可以获得焓',
    ' Enthalpy, which increases Entropy gain by ': '焓，因此熵获取速度乘以',
    ' Entropy': '熵',
    'Evaporate your mass of Black Hole to gain Hawking Radiation': '消耗黑洞质量可以获得黑洞辐射',
    ' Hawking Radiation, which increases Entropy cap to ': '黑洞辐射，因此熵上限增加至',
    'Next at': '下一级需要',
    'Entropic Multiplier': '熵加倍',
    'Meta Tickspeed, BHC & Cosmic Ray start ': '时间速度、黑洞压缩器和宇宙射线的元折算延迟',
    ' later.': '出现。',
    'Entropic Accelerator': '熵加速',
    'Atomic Power’s effect is ': '原子能量的效果指数增加',
    ' exponentially stronger.': '。',
    'Entropic Evaporation': '熵消耗',
    'Make evaporated resources gain ': '消耗资源后，使相应资源获取速度变为原来的',
    ' faster.': '。',
    'Entropic Converter': '熵转化',
    'Tickspeed Power gives ': '使黑洞压缩器和宇宙射线的倍率增加时间速度倍率的',
    ' boost to BHC & Cosmic Ray Powers.': '。',
    'Entropic Booster': '熵助推',
    'Entropic Scaling': '熵折算',
    'All pre-Supernova, pre-Pent & pre-Meta scalings are ': '使超新星之前(五重阶层之前)所有资源的折算在元折算之前弱化',
    ' weaker.': '。',
    'Entropic Condenser': '熵压缩',
    'Entropy boosts itself by ': '熵使自身增加',
    'Entropic Radiation': '熵辐射',
    'Radiation effects are boosted by ': '使辐射波的效果基于熵数量变为原来的',
    ' based on Entropy.': '。',
    'Stop Evaporating to get': '停止消耗，获得',
    'best Enthalpy': '焓(以最高一次为准)',
    'best Hawking Radiation': '黑洞辐射(以最高一次为准)',
    //#endregion
    //#region 黑暗
    'require Og-118': '需要购买气奥118Og',
    ' Dark Ray.': '暗射线。',
    ' Boosts dark shadows gain by ': '使黑暗之影获取速度变为原来的',
    ' Dark Shadow.': '黑暗之影。',
    'Boosts mass gain by ': '使质量获取速度变为原来的',
    'Boosts dark ray gain by ': '使暗射线获取速度变为原来的',
    'Boosts blueprint particles gain by ': '使蓝图粒子获取速度变为原来的',
    'Makes you becoming ': '使您前往超新星的次数变为原来的',
    ' more supernovas': '',
    'Boosts entropy earned by ': '使熵获取速度变为原来的',
    'Boosts abyssal blots earned by ': '使深渊之渍获取速度变为原来的',
    'Boosts exponent from the mass of BH formula by ': '使黑洞质量公式中的指数',
    'Uncaps BH-Exponent Boost\'s effect': '移除黑洞指数加成效果的上限',
    ' Abyssal Blot.': '深渊之渍。',
    'Boosts dark shadows gain by ': '使黑暗之影获取速度变为原来的',
    'Makes mass gain softcaps 4-6 start ': '使质量获取速度的四重软上限至六重软上限延迟',
    'Makes mass gain softcaps 4-8 start ': '使质量获取速度的四重软上限至八重软上限延迟',
    ' later': '出现',
    'Boosts hawking radiation gain by ': '使黑洞辐射获取速度变为原来的',
    'Boosts prestige base\'s multiplier by ': '使转生基础值变为原来的',
    'Boosts cosmic string\'s power by ': '使宇宙弦倍率变为原来的',
    'Boosts all matters gain by ': '使所有物质获取速度变为原来的',
    'Boosts accelerator power by ': '使加速器倍率变为原来的',
    'Atomic power & quark overflows start ': '使原子能量和夸克的溢出延迟',
    'Final Star Shards are ': '使最终星辰碎片强化',
    'Raises Exotic Atom\'s formula by ': '使奇异原子的公式增加',
    'Passively gains ': '每秒获得暗射线，数量为重置时获取数量的',
    ' of dark rays gained on reset per second': '',
    'Earns ': '使雕文获取数量变为原来的',
    ' more glyphic mass': '',
    'Adds ': '增加',
    ' more C13-15 maximum completions': '次挑战13-挑战15的次数上限',
    'Next Ray\'s effect at ': '下个暗射线效果需要',
    'Next Shadow\'s effect at ': '下个黑暗之影效果需要',
    'Next Abyssal Blot\'s effect at ': '下个深渊之渍效果需要',
    'Start Dark Run': '开始黑暗狂奔',
    'Exit Dark Run': '退出黑暗狂奔',
    'Glyph Button Mode': '雕文按钮模式',
    'Clear all glyphs': '清除所有雕文',
    'Earning': '获取',
    'Max Earning': '至多获取',
    'Clear Glyph': '清除雕文',
    ' to maximum gain any glyph': '至多获取雕文数量',
    'Raise mass gain by 1.5 every level.': '每级使质量获取速度变为原来的1.5次方。',
    'Raise mass of black hole gain by 1.5 every level.': '每级使黑洞质量获取速度变为原来的1.5次方。',
    'Exotic rank starts x1.25 later every level.': '每级使级别的奇异折算延迟1.25倍出现。',
    'Rank tiers\' nerf power from 8th QC modifier is weaker while dark running.': '在黑暗狂奔中，使量子挑战8对级别阶层的削弱变得更弱。',
    'Raise atom gain by 1.5 every level.': '每级使原子获取速度变为原来的1.5次方。',
    'Triple dark ray gain for each level.': '每级使暗射线获取速度变为原来的3倍。',
    'Gain x1.5 more Cyrillic Glyphs.': '西里尔雕文的获取数量变为原来的1.5倍。',
    'Dilated mass\'s overflow starts ^10 later every level.': '每级使膨胀质量的溢出延迟10次方出现。',
    'Star generators are ^1.5 stronger every level.': '每级使星辰发生器的速度变为原来的1.5次方。',
    'Prestige base\'s exponent is increased by 0.02 per level.': '每级使转生基础值的指数增加0.02。',
    'Add 0.1 to matter exponent.': '使物质的指数增加0.1。',
    'Cosmic ray effect is now an exponent at a super reduced rate.': '使宇宙射线效果变为指数加成，但效果倍率超级降低。',
    'Green Chromas gain is squared.': '使绿色色度获取速度变为原来的平方。',
    'Each matter\'s exponent is increased by 12.5% per level.': '每级使每种物质的指数增加12.5%。',
    'lg(lg(x)': 'lg(lg(x)',
    ' to each matter gain by previous matter.': '为前一种物质对后一种物质获取速度的加成。',
    'Max All Upgrades': '最大化购买所有升级',
    'Tip: Reach ': '提示：当前物质到达',
    ' of current matter to unlock next matter!': '后可以解锁下一种物质！',
    ' Dark Matter': '暗物质',
    ' Red Matter': '红色物质',
    ' Magenta Matter': '品红色物质',
    ' Pink Matter': '粉色物质',
    ' Purple Matter': '紫色物质',
    ' Violet Matter': '蓝紫色物质',
    ' Blue Matter': '蓝色物质',
    ' Cyan Matter': '青色物质',
    ' Green Matter': '绿色物质',
    ' Lime Matter': '黄绿色物质',
    ' Yellow Matter': '黄色物质',
    ' Orange Matter': '橙色物质',
    ' White Matter': '白色物质',
    ' Fading Matter': '褪色物质',
    'Boost Dark Matter gain.': '增加暗物质获取速度。',
    'Boost Red Matter gain.': '增加红色物质获取速度。',
    'Boost Magenta Matter gain.': '增加品红色物质获取速度。',
    'Boost Pink Matter gain.': '增加粉色物质获取速度。',
    'Boost Purple Matter gain.': '增加紫色物质获取速度。',
    'Boost Violet Matter gain.': '增加蓝紫色物质获取速度。',
    'Boost Blue Matter gain.': '增加蓝色物质获取速度。',
    'Boost Cyan Matter gain.': '增加青色物质获取速度。',
    'Boost Green Matter gain.': '增加绿色物质获取速度。',
    'Boost Lime Matter gain.': '增加黄绿色物质获取速度。',
    'Boost Yellow Matter gain.': '增加黄色物质获取速度。',
    'Boost Orange Matter gain.': '增加橙色物质获取速度。',
    'Boost White Matter gain.': '增加白色物质获取速度。',
    'Require': '需',
    'Reset dark shadows, abyssal blots, matters, and force darkness reset for a final star shard. It boosts matters gain and glyphic mass.': '重置黑暗之影、深渊之渍和物质，并强制融入黑暗，以获得最终星辰碎片。它可以加成物质获取速度和雕文获取数量。',
    ' FSS base': '最终星辰碎片基础值',
    'Your best mass of black hole in the 16th Challenge is ': '您在挑战16中最高的黑洞质量为',
    'You must purchase corruption upgrades outside C16!': '您需要在挑战16之外才能购买腐化升级！',
    'Multiply all matters gain by 1e10, and square mass of black hole gain.': '使所有物质获取速度变为1e10倍，并使黑洞质量获取速度变为原来的平方。',
    'Unlock the Unstable Black Hole that boosts normal black hole. (in black hole tab)': '在黑洞子选项卡下解锁了不稳定黑洞，可以增加黑洞质量获取速度。',
    'Unstable Black Hole\'s effect is 50% stronger. (after overflow)': '使不稳定黑洞的效果增加50%。(在计算完溢出之后的数值)',
    'Remove all pre-Meta scalings from Supernova. [Neut-Muon]\'s effect is now changed. Denullify C5\'s effect, but it\'s changed.': '移除超新星所有元折算之前的折算。使[缪中微子]的效果发生变化。使挑战5的奖励重新生效，但效果发生变化。',
    'Dark Shadow\'s first reward is overpowered. Remove all scalings from Tickspeed, but nullify [Tau]\'s effect.': '使黑暗之影的第一个效果变得滥强。移除时间速度的所有折算，但也使[陶子]失效。',
    'Unlock Exotic Atoms in Atom tab, and unlock new elements\' layer.': '在原子选项卡下解锁奇异原子，并解锁新的元素层级。',
    'Remove all scalings from BHC. [Neut-Tau]\'s effect no longer affects BHC\'s cheapness. In C16, BHC is 1,000,000x cheaper.': '移除黑洞压缩器的所有折算。使[陶中微子]的效果不再影响黑洞压缩器。在挑战16中，使黑洞压缩器便宜1e6倍。',
    'Remove all scalings from Cosmic Ray. [Neut-Tau]\'s effect now re-affects BHC\'s cheapness, but its effect is MASSIVELY weaker.': '移除宇宙射线的所有折算。使[陶中微子]的效果重新影响黑洞压缩器，但效果极度弱化。',
    'Remove all scalings from Tetr. However, Hybridized Uran-Astatine\'s first effect no longer affects it. Tetr is 500x cheaper in C16.': '移除四重阶层的所有折算。但铀砹混合物的第一个效果也不再对它生效。在挑战16中，使四重阶层便宜500倍。',
    'De-corrupt 40th, 64th, 67th, 150th, 199th, 200th, and 204th elements.': '使锆(40Zr）、钆(64Gd)、钬(67Ho)、Unpentnilium(150Upn)、Unennennium(199Uee)、Binilnilium(200Bnn)、Binilquadium(204Bnq)不再腐化。',
    'Requires': '需',
    ' Corrupted Shard.': '腐化碎片。',
    //#endregion
    //#region 无限
    'Your mass is enough to go Infinity!': '您的质量已经足以前往无限了！',
    'You have reached the limit of lifting where only gods withstand... You need to condense all your progress to evolve!': '您已经到达了只有神明才能涉足的领域……是时候浓缩一切，继续前进了！',
    'Get Infinity Theorem': '获得无限定理',
    'Theorem Selection': '选择定理',
    ' (hover': '(鼠标停留在上方可以查看信息',
    ' of normal mass to show theorems that you will choose.': '质量后可以显示供选择的定理。',
    'Any Theorem\'s Level is ': '所有定理的等级为',
    'The Core': '核心',
    'Are you sure you want to pick theorem out of core?': '您确定要将该定理移出核心吗？',
    '[Note: 2 or more theorems of any type CANNOT fit in the Core at the same time]': '[注意：相同类型的定理至多只能有一个置入核心]',
    'Inventory': '物品栏',
    'Your inventory is maxed! You need to remove unused or useless theorem...': '您的物品栏满了！您需要移除不再使用或者无用的定理……',
    'Remove selected theorem in inventory': '移除物品栏中所选择的定理',
    'Are you sure you want to remove the selected theorem?': '您确定要移除所选择的定理吗？',
    'Newton Theorem': '牛顿定理',
    'Boost normal mass gain.': '增加质量获取速度。',
    'Boost normal mass overflow starting.': '使质量的溢出延迟出现。',
    'Make pre-beyond ranks cheaper.': '使超-级别之前的所有级别变得更便宜。',
    'Increase the exponent of prestige base.': '增加转生基础值的指数。',
    'Normal Mass': '质量',
    'Hawking Theorem': '霍金定理',
    'Boost mass of BH gain (weaker in C16).': '增加黑洞质量获取速度(在挑战16中弱化)。',
    'Boost BH mass overflow starting (weaker in C16).': '使黑洞质量的溢出延迟出现(在挑战16中弱化)。',
    'Weaken unstable BH decreasing.': '使不稳定黑洞的获取速度减少变得更缓和。',
    'Boost FVM\'s power.': '增加假真空操控器倍率。',
    'Mass of Black Hole': '黑洞质量',
    'Dalton Theorem': '道尔顿定理',
    'Boost quarks gain.': '增加夸克获取速度。',
    'Boost quark & atomic power overflows starting.': '使夸克和原子能量的溢出延迟出现。',
    'Increase overpower\'s power.': '增加降伏器倍率。',
    'Increase accelerator\'s power.': '增加加速器倍率。',
    'Exotic Atom': '奇异原子',
    'Protoversal Theorem': '原初宇宙定理',
    'Make cosmic string cheaper.': '使宇宙弦变得更便宜。',
    'Strengthen primordium particles.': '使原基定理的效果变得更好。',
    'Weaken each “entropic” reward scaling.': '使“熵”所有奖励效果的折算弱化。',
    'Weaken QC modifications.': '使量子挑战的削弱变得更缓和。',
    'Einstein Theorem': '爱因斯坦定理',
    'Boost pre-infinity global speed.': '增加无限之前所有资源获取速度。',
    'Boost pre-quantum global speed.': '增加量子之前所有资源获取速度。',
    'Boost dark shadow & abyssal blot gains.': '增加黑暗之影和深渊之渍的获取速度。',
    'Weaken each glyphic mass nerfing.': '使雕文质量的削弱变得更缓和。',
    'Based on ': '基于',
    'Place any theorem in core to show effects!': '将任意定理置入核心后即可显示效果！',
    'Are you sure you want to go infinity without selecting any theorem?': '您确定要在不选择任何定理的前提下前往无限吗？',
    'Require-Free Tree': '条件无视树',
    ' Upgrades in pre-corrupted tree can be bought without their requirement.': '腐化之前的中子树升级可以无视条件进行购买。',
    'Infinity Mass': '无限质量',
    ' Normal mass & BH mass gains are boosted by total infinity points.': '使总无限点数可以加成质量和黑洞质量的获取速度。',
    'Legacy Mass Upgrade 4': '传承质量升级4',
    ' Start with overpower unlocked, its starting cost is massively decreased (likewise, start with Binilbium-202 unlocked).': '初始状态下就解锁降伏器，且它的初始花费极度下降(初始状态下就解锁Binilbium(202Bnb))。',
    'Dark Rest': '黑暗休整',
    ' Keep glyph upgrades on infinity (likewise, start with Unhexunium-161 unlocked).': '前往无限时保留雕文升级(初始状态下就解锁Unhexunium(161Uhu))。',
    'Tree Automation': '自动化树',
    ' Automate pre-corrupted tree.': '您可以自动购买腐化之前的中子树升级。',
    'Self-Infinity': '自助无限',
    ' Infinity theorem boosts infinity points gain.': '使无限定理可以加成无限点数获取速度。',
    'Stop Big Rip Switching': '停止大撕裂切换',
    ' Pre-218 big rip elements are now affordable outside Big Rip. Automate elements tier 2 (119th-218th).': '您可以在大撕裂外购买第218号元素之前需进入大撕裂的元素。您可以自动购买元素阶层2(从第119号至第218号)的元素。',
    'Dark Passive': '被动之暗',
    ' Start with more dark rays (like dark ray’s first reward unlocked).': '初始状态下就获得更多暗射线(直接解锁暗射线的第一个效果)。',
    'Corrupted Construction': '腐化建造',
    ' Start with rows of upgrades bought in corrupted tree (based on infinity theorems, starting at 2, ending at 5).': '初始状态下就视为已经购买了相应行数的腐化中子树升级(数量基于无限定理，初始为2，最终为5)。',
    ' Unlock new generator in Main tab. Also, passively generate Dimensional Mass that increases meta-score of equipped theorems.': '在主要面板下解锁新的发生器。另外，自动产生维度质量，它可以增加已装备定理的综合评分。',
    'Final Star Automation': '自动最终星辰',
    ' Automate final star shard, and it doesn’t reset anything. Also, start with beyond-ranks automation.': '您可以自动购买最终星辰碎片，且它不再重置任何东西。另外，初始状态下您就可以自动购买超-级别。',
    'Lethal Universe': '致命宇宙',
    ' Keep big rip upgrades and breaking dilation on infinity.': '前往无限时保留大撕裂升级和撕裂膨胀。',
    'Dark Challenge Automation': '自动黑暗挑战',
    ' Automate challenges 13-15.': '您可以自动完成挑战13-挑战15。',
    'Exotic Speed': '奇异速度',
    ' Infinity Theorems boost kaon and pion gains.': '使无限定理可以加成K介子和π介子的获取速度。',
    'Muonic Automation': '自动μ子',
    ' Automate muonic elements and muon-catalyzed fusion.': '您可以自动购买μ子元素和μ子催化聚变阶层。',
    'Corrupted Peak': '腐化之巅',
    ' Start with C16 unlocked. Keep corruption upgrades and best BH in C16 on infinity. Unlock more corruption upgrades.': '初始状态下就解锁挑战16。前往无限时保留腐化升级和挑战16中最高的黑洞质量。解锁更多腐化升级。',
    'Break Infinity': '打破无限',
    ' Reaching infinity no longer plays animation. You can lift beyond normal mass limit and get infinity theorems freely. Finally, unlock Element Tier 3, more Muonic Elements.': '满足无限的条件时不再播放动画。您可以超越质量上限并自由获得无限定理。最后，您还可以解锁元素阶层3和更多μ子元素。',
    '[COMING AFTER RELEASE]': '[之后推出]',
    '': '',
    ' Infinity Points. Hover any upgrade to see its description.': '无限点数。鼠标停留在升级上方可以查看详情。',
    //#endregion
    //#region 选项
    'Game Data got NaNed': '游戏数据出错了',
    'Save': '保存',
    'Game Saved': '游戏进度已保存',
    'Hard Reset': '硬重置',
    'Export': '导出',
    'Error Exporting, because it got NaNed': '导出失败，游戏数据有误',
    'Export to clipboard': '导出到剪贴板',
    'Copied to Clipboard': '已导出至剪贴板',
    'Import': '导入',
    'Error Importing': '输入有误，导入失败',
    'Join Discord': '加入Discord频道',
    'Donate': '捐赠',
    'Help': '帮助',
    'Offline Production': '离线产量',
    'Fonts': '字体',
    'Notations': '记数法',
    'Elemental': '元素记数法',
    'Engineering': '工程记数法',
    'Mixed Scientific': '混合科学记数法',
    'Prestige Layer': '转生层级记数法',
    'Scientific': '科学记数法',
    'Standard': '普通记数法',
    'Old Scientific': '旧科学记数法',
    'Omega': 'Omega记数法',
    'Omega Short': 'Omega Short记数法',
    'Tree Animation': '中子树动画',
    'Circle': '圆形',
    'Square': '方块',
    'Mass Format Display': '质量显示格式',
    'Default': '默认',
    'Always show g': '总是以克为单位',
    'Always show mlt': '总是以多宇宙为单位',
    'Important units only': '只显示重要的单位',
    'Confirmation Settings': '确认窗口设置',
    'Ok': '好',
    '\n            Congratulations!': '恭喜！',
    'You have becomed 10 Supernovas!': '您已经有10次前往超新星了！',
    'And you can manualy supernova!': '您可以手动前往超新星了！',
    'Bosons are unlocked in Supernova tab!': '另外，超新星选项卡下解锁了玻色子！',
    'You have beated Challenge 10!': '您已经通过了挑战10！',
    'Fermions are unlocked in Supernova tab!': '超新星选项卡下解锁了费米子！',
    'You need to go Quantum!': '您需要前往量子了！',
    'Mass has collapsed while going Quantum! It looks like evaporation! But at what cost?\n        ': '前往量子时质量坍缩了！看起来就像是蒸发了一样，不知道代价又是什么？',
    'Uhh Oh': '啊这……',
    'Don’t worry, new mechanics will arrive for you!\n        ': '别担心，新机制就要来了！',
    'Cool': '酷毙啦',
    'Entropy is unlocked in Quantum tab!': '量子选项卡下解锁了熵！',
    'Let\'s Go!': '出发吧！',
    'Chapter 1: The First Lift': '第1章：初次举起',
    'Your potential of gaining weight starts here. How much mass can you gain?\n    ': '您获得质量的旅途从此开始。您能够获得多少质量呢？',
    'Chapter 2: Rage Power': '第2章：狂怒能量',
    'You feel outrageous and want to be energy-efficient. You are stronger with less effort needed.\n    ': '您狂怒不止，想要提高效率。花费的功夫越少，您就越强。',
    'Chapter 3: The Black Hole': '第3章：黑洞',
    'You pulled up a hidden mystery of cosmos. The force was so strong, it forms a black hole!\n    ': '您揭开了宇宙隐藏的奥秘。这股力量强大到形成了黑洞！',
    'Chapter 4: The Atom': '第4章：原子',
    'You discovered a Atom! You decompose it to find a physical miracle: Gravity. This helps you to go further!\n    ': '您发现了原子！您将它进行分解，并发现了物理学的奇迹：重力。它可以让您走得更远！',
    'Chapter 5: Supernova Born': '第5章：超新星诞生',
    'A new age of stars rises, while the stars collapsed.  Neutron stars felt elder...\n    ': '有星辰坍缩，也有新的星辰诞生。连中子星都感觉变得更老了……',
    'Chapter 6: The Radiation': '第6章：辐射波',
    'As stars radiate, you dig deeper: Radiation.\n    ': '您对星辰的辐射进行了更深入的研究，结果就是它了。',
    'Chapter 7: Scale to Quantum': '第7章：到达量子尺度',
    'Mass has collapsed in quantum scale! Good luck on new features!\n    ': '质量已经坍缩到量子尺度了！祝您好运！',
    'Chapter 8: Ripping Universe': '第8章：撕裂宇宙',
    'All the spacetime rips before your eyes!\n    ': '时空在您的面前被撕裂！',
    'Chapter 9: Trapped in Darkness': '第9章：困于黑暗',
    'You rose up the darkness. Time to research the mysteries of matter!\n    ': '黑暗就此出现。是时候研究物质的奥秘了！',
    'Chapter 10: The Corruption': '第10章：腐化',
    'The final challenge stands against you. Good luck!\n    ': '这是您最后的挑战。祝您好运！',
    'Chapter 11: The Infinity': '第11章：无限',
    'Infinity. You have been evolved to a god.\n    ': '无限……您进化成神了。',
    'Chapter 12: Broken Infinity': '第12章：打破无限',
    'Your omnipotence ascends as you surpass Infinity.\n    ': '随着您超过无限，您的全能更上一层楼了。',
    'Incremental Mass Rewritten v0.7 - made by MrRedShark77': '质量增量重制版v0.7 - 作者为MrRedShark77，由by22dgb汉化',
    'The game is inspired by Distance Incremental & Synergism': '本游戏灵感来自于距离增量及协同放置',
    'Contributors': '特别鸣谢',
    'Lemon': 'Lemon',
    ', 16777216 & Aarex (Artists': '，16777216和Aarex(帮助制作图片',
    'Hint 1: Hover top image above tabs to show description...': '提示1：鼠标停留在选项卡上方的图片可以查看详情……',
    'Total time played': '游戏总时间',
    //#endregion
}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    ": ": "：",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "：",
    "： ": "：",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    "\n": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?(e[+\-]?\d?\.?\d+)?(e\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\s\d+(e\.\,\d+)?[A-Za-z]{0,4}(.*)$/, //处理数字及单位
    /^\/?\^?\d+[e\.\,\d\/]+$/, //处理数字及单位
    /^[e\.\,\d]+ \+ [e\.\,\d]+$/, //处理数字及单位
    /^[A-Z][a-z]?$/, //单独处理短文字
    /^(.*)[\u4E00-\u9FFF]+(.*)$/, //不抓取内容
    /^e\d\.[e\d]+e\d+$/, //不抓取内容
    /^\^?e[e\.\,\d]+$/, //不抓取内容
    /^×?[\d:]+\d+.\d$/, //不抓取内容
    /^×\d+.\d+e[\,\d]+$/, //不抓取内容
    /^[x×]\d[.,]\d+e?\d+$/, //不抓取内容
    /^U[a-z]{2}$/, //不抓取内容
    /^\d+\(\+\d+$/, //不抓取内容
    /^ = \d.\d+e[\.\,\d]+$/, //不抓取内容
    /^[\d\,]*\d{1,3}arv\^\d+$/, //不抓取内容
    /^[\d:]*\d{2}.\d{2}$/, //不抓取内容
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^\s*Cost$/, '需'], //主界面等
    [/^\s*Req$/, '需求'], //主界面等
    [/^\s*Muscler Power$/, '锻体器倍率'], //主界面等
    [/^\s*Muscler Effect$/, '锻体器效果'], //主界面等
    [/^\s*Booster Power$/, '助推器倍率'], //主界面等
    [/^\s*Booster Effect$/, '助推器效果'], //主界面等
    [/^x(.+) to Muscler Power$/, 'x$1倍锻体器倍率'], //主界面等
    [/^\s*Stronger Power$/, '强化器倍率'], //主界面等
    [/^\s*Stronger Effect$/, '强化器效果'], //主界面等
    [/^\^(.+) to Booster Power\s*$/, '^$1助推器倍率'], //主界面等
    [/^\s*Overpower Power$/, '降伏器倍率'], //主界面等
    [/^\s*Overpower Effect$/, '降伏器效果'], //主界面等
    [/^\^(.+) to Stronger Power\s*$/, '^$1强化器倍率'], //主界面等
    [/^Unlock new type of Stars, require (.+) Quark$/, '解锁新的星辰，需$1夸克'], //主界面等
    [/^Boost all-Star resources gain, require (.+) Quark$/, '加成所有星辰相关资源的获取速度，需$1夸克'], //主界面等
    [/^Base: (.+)x$/, '基础值：$1倍'], //主界面等
    [/^Reach over (.+) collapsed stars to go Supernova$/, '坍缩星辰不少于$1时就可以前往超新星了'], //主界面等
    [/^Cost: (.+)Rage Power$/, '花费：$1狂怒能量'], //升级等
    [/^Cost: (.+)Dark Matter$/, '花费：$1暗物质'], //升级等
    [/^Cost: (.+)Atom$/, '花费：$1原子'], //升级等
    [/^Cost: (.+)Death Shard$/, '花费：$1死寂碎片'], //升级等
    [/^Currently: \+(.+) Musclers$/, '目前效果：增加$1锻体器'], //升级等
    [/^Currently: \+(.+) Boosters$/, '目前效果：增加$1助推器'], //升级等
    [/^Currently: \+(.+) Stronger$/, '目前效果：增加$1强化器'], //升级等
    [/^Currently: x(.+) later$/, '目前效果：延迟$1倍出现'], //升级等
    [/^Currently: x(.+) cheaper$/, '目前效果：减少$1倍'], //升级等
    [/^Currently: x(.*)$/, '目前效果：倍率为$1'], //升级等
    [/^Currently: \+(.+) later\s*$/, '目前效果：延迟$1次出现'], //升级等
    [/^Currently: (.+)x later$/, '目前效果：延迟$1倍出现'], //升级等
    [/^You have (.+) Rage Power$/, '您拥有$1狂怒能量'], //升级等
    [/^You have (.+) Dark Matter$/, '您拥有$1暗物质'], //升级等
    [/^You have (.+) Atom$/, '您拥有$1原子'], //升级等
    [/^You have (.+) Death Shard$/, '您拥有$1死寂碎片'], //升级等
    [/^Finish Challenge for \+(.+) Completions$/, '完成挑战，使完成次数增加$1次'], //挑战等
    [/^Currently: \+(.+) later to Super Rank starting, (.+)% weaker to Super Tickspeed scaling$/, '目前效果：使级别的超级折算延迟$1次出现，时间速度的超级折算弱化$2%'], //挑战等
    [/^Currently: ×(.+) later to Supercritical Rank & All Fermions starting, (.+) weaker to Super Overpower scaling$/, '目前效果：使级别和所有费米子的超临界折算延迟$1倍出现，降伏器的超级折算弱化$2%'], //挑战等
    [/^Currently: \+(.+)%\s?$/, '目前效果：增加$1%'], //挑战等
    [/^Currently: \^(.+) later$/, '目前效果：延迟$1次方出现'], //原子等，前置
    [/^Currently: \^(.*)$/, '目前效果：^$1'], //挑战等
    [/^Currently: (.+) weaker\s?$/, '目前效果：降低$1'], //挑战等
    [/^Currently: \+(.+)x\s?$/, '目前效果：增加$1倍'], //挑战等
    [/^Currently: \+(.+) to Rage Power Upgrade 7$/, '目前效果：狂怒升级7的效果增加$1'], //原子等，前置
    [/^Currently: \+(.+)$/, '目前效果：增加$1'], //挑战等
    [/^Boost Mass gain by (.+)x$/, '使质量获取速度变为原来的$1倍'], //原子等
    [/^Boost Mass gain by \^(.*)$/, '使质量获取速度变为原来的$1次方'], //原子等
    [/^Increases Tickspeed Power by (.+)%$/, '使时间速度倍率增加$1%'], //原子等
    [/^Boost Rage Power gain by (.+)x$/, '使狂怒能量获取速度变为原来的$1倍'], //原子等
    [/^Boost Rage Power gain by \^(.*)$/, '使狂怒能量获取速度变为原来的$1次方'], //原子等
    [/^Boost Mass gain based on Rage Powers - \^(.*)$/, '使狂怒能量可以加成质量获取速度 - 倍率为$1次方'], //原子等
    [/^Boost Mass gain based on Rage Powers - (.+)x$/, '使狂怒能量可以加成质量获取速度 - 倍率为$1倍'], //原子等
    [/^Boost Dark Matter gain by (.+)x$/, '使暗物质获取速度变为原来的$1倍'], //原子等
    [/^Boost Dark Matter gain by \^(.*)$/, '使暗物质获取速度变为原来的$1次方'], //原子等
    [/^Increases BH Condenser Power by\s*(.*)$/, '使黑洞压缩器倍率增加$1'], //原子等
    [/^ Protons Powers, which:\s*$/, '质子能量，因此获得以下效果：'], //原子等
    [/^ Neutrons Powers, which:\s*$/, '中子能量，因此获得以下效果：'], //原子等
    [/^ Electrons Powers, which:\s*$/, '电子能量，因此获得以下效果：'], //原子等
    [/^Currently: (.+)x\s?$/, '目前效果：$1倍'], //原子等
    [/^Currently: (.+)x, \^(.+)$/, '目前效果：$1倍，且^$2'], //原子等
    [/^Currently: (.+)x stronger$/, '目前效果：增加$1倍'], //原子等
    [/^Currently: (.+) later$/, '目前效果：延迟$1次出现'], //原子等
    [/^Currently: ×(.+)$/, '目前效果：$1倍'], //原子等
    [/^\s*\[Level $/, '[等级：'], //原子等
    [/^Cancel for (.+) Relativistic particles$/, '取消质量膨胀后可获得$1相对论粒子'], //原子等
    [/^\s+Gain more Dark Matters & Mass from Black Hole based on Photon.$/, '基于光子的数值，增加暗物质和黑洞质量的获取速度。'], //超新星等
    [/^\s+Boost BH Condenser Power.$/, '增加黑洞压缩器倍率。'], //超新星等
    [/^\s+Photons gain is boosted by Collapsed Star.$/, '使坍缩星辰可以加成光子获取速度。'], //超新星等
    [/^\s+All-Star resources gain is boosted by Photon.$/, '使光子可以加成所有星辰相关资源的获取速度。'], //超新星等
    [/^\s+Gain more Atoms & Atomic Powers based on Gluon.$/, '基于胶子的数值，增加原子获取速度及原子能量。'], //超新星等
    [/^\s+Boost Cosmic Ray Power.$/, '增加宇宙射线倍率。'], //超新星等
    [/^\s+Gluons gain is boosted by Quark.$/, '使夸克可以加成胶子获取速度。'], //超新星等
    [/^\s+Supernova requirement is decreased based on Gluon.$/, '基于胶子的数值，降低超新星的需求。'], //超新星等
    [/^\s+Currently$/, '目前效果'], //超新星等
    [/^Adds (.+) free Cosmic Rays$/, '增加$1个免费宇宙射线'], //超新星等
    [/^x(.+) to Relativistic Particles gain$/, '使相对论粒子获取速度变为原来的$1倍'], //超新星等
    [/^ Boson's first effect is (.+)% stronger$/, '玻色子的第一个效果增加$1%'], //超新星等
    [/^4th Photon & Gluon upgrades are (.+)x stronger$/, '使光子和胶子升级4增加$1倍'], //超新星等
    [/^Radiation Boosters are (.+)x cheaper$/, '使辐射波升级便宜$1倍'], //超新星等
    [/^Meta-Tickspeed starts (.+)x later$/, '使时间速度的元折算延迟$1倍出现'], //超新星等
    [/^Dark ray's effect is \^(.+) stronger$/, '使暗射线的效果变为原来的$1次方'], //超新星等
    [/^Collapsed Stars gain softcap starts \^(.+) later$/, '使坍缩星辰获取速度的软上限延迟$1次方出现'], //超新星等
    [/^x(.+) to Higgs Bosons & Gravitons gain$/, '使希格斯玻色子和引力子的获取速度变为原来的$1倍'], //超新星等
    [/^Tickspeed is (.+)x cheaper \(before Meta scaling$/, '使时间速度便宜$1倍(在元折算前生效'], //超新星等
    [/^Tier requirement is (.+)x cheaper$/, '使阶层的需求便宜$1倍'], //超新星等
    [/^Pre-Meta-Supernova Scalings are (.+)% weaker$/, '使超新星元折算之前的所有折算弱化$1%'], //超新星等
    [/^Meta & Exotic Supernovas scale (.+) weaker$/, '使超新星的元折算和奇异折算弱化$1'], //超新星等
    [/^Pre-Meta BH Condensers & Cosmic Rays are (.+)x cheaper$/, '使黑洞压缩器和宇宙射线在元折算之前的部分便宜$1倍'], //超新星等
    [/^Increase prestige base's exponent by (.+)$/, '使转生基础值的指数增加$1'], //超新星等
    [/^Radio wave is boosted by (.+)x \(based on Frequency$/, '使无线电波的获取速度变为原来的$1倍(基于频率的数值'], //超新星等
    [/^Non-bonus tickspeeds are (.+)x stronger$/, '使非加成的时间速度增加$1倍'], //超新星等
    [/^Mass softcap\^3 starts \^(.+) later$/, '使质量获取速度的三重软上限延迟$1次方出现'], //超新星等
    [/^Microwave is boosted by (.+)x \(based on Radio$/, '使微波的获取速度变为原来的$1倍(基于无线电波的数值'], //超新星等
    [/^Exponent from the mass of BH formula is increased by (.+)$/, '使黑洞质量公式中的指数增加$1'], //超新星等
    [/^Non-bonus BH condenser is (.+)x stronger$/, '使非加成的黑洞压缩器增加$1倍'], //超新星等
    [/^Infrared is boosted by (.+)x \(based on Microwave$/, '使红外线的获取速度变为原来的$1倍(基于微波的数值'], //超新星等
    [/^1st Photon & Gluon upgrades are (.+)x stronger$/, '使光子和胶子升级1增加$1倍'], //超新星等
    [/^Add (.+) levels to all above boosts$/, '使上方所有加成的等级增加$1级'], //超新星等
    [/^Visible is boosted by (.+)x \(based on Infrared$/, '使可见光的获取速度变为原来的$1倍(基于红外线的数值'], //超新星等
    [/^Cosmic Ray power is boosted by (.+)x$/, '使宇宙射线倍率变为原来的$1倍'], //超新星等
    [/^Neutron Star is boosted by (.+)x \(based on Frequency$/, '使中子星的获取速度变为原来的$1倍(基于频率的数值'], //超新星等
    [/^Ultraviolet is boosted by (.+)x \(based on Visible$/, '使紫外线的获取速度变为原来的$1倍(基于可见光的数值'], //超新星等
    [/^Tickspeed power's softcap starts (.+)x later$/, '使时间速度倍率的软上限延迟$1倍出现'], //超新星等
    [/^Meta-Rank starts (.+)x later$/, '使级别的元折算延迟$1倍出现'], //超新星等
    [/^X-ray is boosted by (.+)x \(based on Ultraviolet$/, '使X射线的获取速度变为原来的$1倍(基于紫外线的数值'], //超新星等
    [/^U-Leptons are (.+)x stronger$/, '使U-轻子增加$1倍'], //超新星等
    [/^Gamma-ray is boosted by (.+)x \(based on X-ray$/, '使伽马射线的获取速度变为原来的$1倍(基于X射线的数值'], //超新星等
    [/^U-Quarks are (.+)x stronger$/, '使U-夸克增加$1倍'], //超新星等
    [/^BH formula softcap starts \^(.+) later$/, '使黑洞质量获取公式的软上限延迟$1次方出现'], //超新星等
    [/^Makes tickspeed power raised to the (.+)th power.$/, '使时间速度倍率变为原来的$1次方。'], //量子等
    [/^Makes all Pre-Pent requirements reduced by (.+)x.$/, '使五重阶层之前的级别和阶层需求减少$1倍。'], //量子等
    [/^Makes all Pre-Pent requirements reduced by (.+)x$/, '使五重阶层之前的级别和阶层需求减少$1倍'], //量子等
    [/^Makes all Pre-Exotic pre-Pent requirements reduced by (.+)x.$/, '使五重阶层之前(奇异折算之前)的级别和阶层需求减少$1倍。'], //量子等
    [/^Makes all Pre-Exotic pre-Pent requirements reduced by (.+)x$/, '使五重阶层之前(奇异折算之前)的级别和阶层需求减少$1倍'], //量子等
    [/^Also, all pre-Exotic pre-Hex scalings are (.+) weaker.$/, '另外，使六重阶层之前的所有奇异折算之前的折算弱化$1。'], //量子等
    [/^Also, all pre-Exotic Rank-Hex scalings are (.+) weaker.$/, '另外，使级别至六重阶层的所有奇异折算之前的折算弱化$1。'], //量子等
    [/^Makes rewards from Challenges 1-8 (.+)x stronger.$/, '使挑战1-挑战8的奖励效果增加$1倍。'], //量子等
    [/^Boost Stronger Power by (.+)x$/, '使强化器倍率变为原来的$1倍'], //量子等
    [/^ Boost Non-Bonus Tickspeed by (.+)x$/, '使非加成的时间速度变为原来的$1倍'], //量子等
    [/^ Boost BH Condenser Power by (.+)x$/, '使黑洞压缩器倍率变为原来的$1倍'], //量子等
    [/^ Boost Cosmic Ray Power by (.+)x$/, '使宇宙射线倍率变为原来的$1倍'], //量子等
    [/^Boost Higgs Boson's effect by (.+)x$/, '使希格斯玻色子的效果变为原来的$1倍'], //量子等
    [/^Add (.+) to base from Fermions gain $/, '使费米子获取速度的基础数量增加$1'], //量子等
    [/^Add (.+) to base from Fermions gain  \/$/, '使费米子获取速度的基础数量增加$1/'], //量子等
    [/^ Add (.+) free tiers to Fermions$/, '使费米子阶层额外增加$1'], //量子等
    [/^Boost all Radiations gains by (.+)x$/, '使辐射波的波长获取速度变为原来的$1倍'], //量子等
    [/^Boost all Radiations gains by (.+)x \/$/, '使辐射波的波长获取速度变为原来的$1倍/'], //量子等
    [/^ Make all Radiations effects (.+)x stronger$/, '使辐射波的效果变为原来的$1倍'], //量子等
    [/^Make pre-exotic Supernova's scalings start (.+) later$/, '使超新星所有奇异折算之前的折算延迟$1次出现'], //量子等
    [/^Make all Supernova's scalings start (.+) later$/, '使超新星的所有折算延迟$1次出现'], //量子等
    [/^Require (.+) Infinity Theorem$/, '需要$1无限定理'], //无限等
]);