/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "Main": "主界面",
    "Mass Upgrades": "质量升级",
    "Options": "选项",
    "Loading game...": "游戏加载中...",
    "Buy Max": "购买最大",
    "Hard Reset": "硬复位",
    "Scaling": "缩放",
    "Ranks Rewards": "段位奖励",
    "Stats": "统计",
    "Stronger [": "更强 [",
    "Stronger Effect": "更强的效果",
    "Stronger Power": "更强的力量",
    "Tickspeed Effect": "时刻速度效果",
    "Tickspeed Power": "时刻速度力量",
    "Tier": "层",
    "triple mass gain.": "三重质量增益。",
    "Upgrades": "升级",
    "Req": "要求",
    "Reset your mass and upgrades, but": "重置你的质量和升级，但是",
    "Booster [": "助推器 [",
    "Booster Effect": "助推器效果",
    "Booster Power": "助推器力量",
    "Cost": "成本",
    "double Rage Powers gain.": "双倍愤怒力量增益。",
    "Muscler [": "肌肉 [",
    "Muscler Effect": "肌肉效果",
    "Muscler Power": "肌肉力量",
    "Rage Points": "愤怒点数",
    "Rage Upgrades": "愤怒升级",
    "raise mass gain by 1.15": "将质量增益提高 1.15",
    "Rank": "段位",
    "make mass gain is boosted by (x+1)^2, where x is rank.": "使质量增益提升到 (x+1)^2 ，其中 x 是段位。",
    "mass upgrade 2 boosts itself. Currently": "质量升级 2 提升它自己。当前",
    "reduce all mass upgrades cost scaled by 20%.": "将所有质量升级成本降低 20%。",
    "reduce mass upgrade 3 cost scaled by 20%.": "将赵林许升级 3 成本降低 20%。",
    "reduce rank reqirements by 20%.": "将段位要求降低 20%。",
    "Tickspeed [": "时刻速度 [",
    "unlock mass upgrade 2, reduce mass upgrade 1 cost scaled by 20%.": "解质量升级 2，减少质量升级 1 成本 20%。",
    "unlock mass upgrade 3, reduce mass upgrade 2 cost scaled by 20%, mass upgrade 1 boosts itself. Currently": "解锁质量升级 3，减少质量升级 2 成本 20%，质量升级 1 提升自身。 当前",
    "x to mass gain": "x 质量增益",
    "adds +5% tickspeed power for every tiers you have, softcaps at +40%. Currently": "为您拥有的每一层增加 +5% 时刻速度力量，软上限为 +40%。 当前",
    "make mass gain is boosted by (x+1)^2, where x is rank. Currently": "使质量增益提升 (x+1)^2，其中 x 是段位。 当前",
    "make mass upgrade 3 softcap starts 1.2x later.": "使质量升级3软上限开始于 1.2x 之后。",
    "make rank 6 effect is better. [(x+1)^2 -> (x+1)^x^1/3]": "使段位6效果更好。 [(x+1)^2 -> (x+1)^x^1/3]",
    "rank up.": "段位提升。",
    "Require 1e9 tonne of mass to reset previous features for gain Rage Powers": "需要 1e9 吨的质量来重置以前的功能以获得愤怒力量",
    "unlock mass upgrade 3, reduce mass upgrade 2 cost scaled by 20%, mass upgrade 1 boosts itself.": "解锁质量升级 3，减少质量升级 2 成本 20%，质量升级 1 提升自身。",
    "): Starts at": "): 开始于",
    " Tickspeed Effect": " 时刻速度效果",
    " Tickspeed Power": " 时刻速度力量",
    "Hint 1: Hover top image above tabs to show description...": "提示 1：将顶部图像悬停在选项卡上方以显示描述...",
    "Join Discord": "加入Discord",
    "mass upgrade 2 boosts itself.": "质量升级 2 提升自身。",
    "The game inspired by Distance Incremental & Synergism": "游戏灵感来自距离增量和协同",
    "adds +5% tickspeed power for every tiers you have, softcaps at +40%.": "为您拥有的每一层增加 +5% 时刻速度，软上限为 +40%。",
    "adds tickspeed power based on ranks. Currently": "根据段位增加时刻速度。 目前",
    "ranks boosts Rage Powers gain. Currently": "段位提升愤怒力量增益。 目前",
    "Super": "超级",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "\t\t\t\t": "\t\t\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) kg$/,
    /^([\d\.]+) g$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Incremental Mass Rewritten v(.+) - made by MrRedShark77$/, '质量增量重制版 v$1 - 由 MrRedShark77 制作'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^unlock mass upgrade ([\d\.]+).$/, '解锁质量升级 $1.'],
	[/^([\d\.]+) g to mass gain$/, '$1 克 到质量增益'],
	[/^([\d\.]+) g\/sec$/, '$1 克\/秒'],
	[/^([\d\.]+) kg\/sec$/, '$1 千克\/秒'],
	[/^([\d\.]+) tonne\/sec$/, '$1 吨\/秒'],
	[/^([\d\.]+)e([\d\.]+) tonne\/sec$/, '$1e$2 吨\/秒'],
	[/^([\d\.]+)e([\d\.]+) tonne to mass gain$/, '$1e$2 吨到质量增益'],
	[/^([\d\.]+) kg to mass gain$/, '$1 kg 到质量增益'],
	[/^([\d\.]+) tonne$/, '$1 吨'],
	[/^([\d\.]+)e([\d\.]+) tonne$/, '$1e$2 吨'],
	[/^\^([\d\.]+) to Booster Power$/, '\^$1 到助推器力量'],
	[/^x([\d\.]+) tonne to mass gain$/, 'x$1 吨到质量增益'],
	[/^x([\d\.]+) to Muscler Power$/, 'x$1 到肌肉力量'],
	[/^x([\d\.]+)e([\d\.,]+) to Muscler Power$/, 'x$1e$2 到肌肉力量'],
	[/^Tier ([\d\.]+)$/, '层 $1'],
	[/^Rank ([\d\.]+)$/, '段位 $1'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);